// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.1.0
// generated at: 2026-05-25 16:34:38 CST

package server

import (
	adminv1 "admin/api/gen/admin/v1"

	"google.golang.org/grpc"
)

type GeneratedGRPCServices struct {
	Api adminv1.ApiServiceServer

	ApiAuditLog adminv1.ApiAuditLogServiceServer

	DataAccessAuditLog adminv1.DataAccessAuditLogServiceServer

	DictEntry adminv1.DictEntryServiceServer

	DictType adminv1.DictTypeServiceServer

	File adminv1.FileServiceServer

	InternalMessage adminv1.InternalMessageServiceServer

	InternalMessageCategory adminv1.InternalMessageCategoryServiceServer

	InternalMessageRecipient adminv1.InternalMessageRecipientServiceServer

	Language adminv1.LanguageServiceServer

	LoginAuditLog adminv1.LoginAuditLogServiceServer

	LoginPolicy adminv1.LoginPolicyServiceServer

	Menu adminv1.MenuServiceServer

	OperationAuditLog adminv1.OperationAuditLogServiceServer

	OrgUnit adminv1.OrgUnitServiceServer

	Permission adminv1.PermissionServiceServer

	PermissionAuditLog adminv1.PermissionAuditLogServiceServer

	PermissionGroup adminv1.PermissionGroupServiceServer

	PolicyEvaluationLog adminv1.PolicyEvaluationLogServiceServer

	Position adminv1.PositionServiceServer

	Role adminv1.RoleServiceServer

	Task adminv1.TaskServiceServer

	Tenant adminv1.TenantServiceServer

	User adminv1.UserServiceServer
}

func RegisterGeneratedGRPCServices(srv grpc.ServiceRegistrar, services GeneratedGRPCServices) {

	if services.Api != nil {
		adminv1.RegisterApiServiceServer(srv, services.Api)
	}

	if services.ApiAuditLog != nil {
		adminv1.RegisterApiAuditLogServiceServer(srv, services.ApiAuditLog)
	}

	if services.DataAccessAuditLog != nil {
		adminv1.RegisterDataAccessAuditLogServiceServer(srv, services.DataAccessAuditLog)
	}

	if services.DictEntry != nil {
		adminv1.RegisterDictEntryServiceServer(srv, services.DictEntry)
	}

	if services.DictType != nil {
		adminv1.RegisterDictTypeServiceServer(srv, services.DictType)
	}

	if services.File != nil {
		adminv1.RegisterFileServiceServer(srv, services.File)
	}

	if services.InternalMessage != nil {
		adminv1.RegisterInternalMessageServiceServer(srv, services.InternalMessage)
	}

	if services.InternalMessageCategory != nil {
		adminv1.RegisterInternalMessageCategoryServiceServer(srv, services.InternalMessageCategory)
	}

	if services.InternalMessageRecipient != nil {
		adminv1.RegisterInternalMessageRecipientServiceServer(srv, services.InternalMessageRecipient)
	}

	if services.Language != nil {
		adminv1.RegisterLanguageServiceServer(srv, services.Language)
	}

	if services.LoginAuditLog != nil {
		adminv1.RegisterLoginAuditLogServiceServer(srv, services.LoginAuditLog)
	}

	if services.LoginPolicy != nil {
		adminv1.RegisterLoginPolicyServiceServer(srv, services.LoginPolicy)
	}

	if services.Menu != nil {
		adminv1.RegisterMenuServiceServer(srv, services.Menu)
	}

	if services.OperationAuditLog != nil {
		adminv1.RegisterOperationAuditLogServiceServer(srv, services.OperationAuditLog)
	}

	if services.OrgUnit != nil {
		adminv1.RegisterOrgUnitServiceServer(srv, services.OrgUnit)
	}

	if services.Permission != nil {
		adminv1.RegisterPermissionServiceServer(srv, services.Permission)
	}

	if services.PermissionAuditLog != nil {
		adminv1.RegisterPermissionAuditLogServiceServer(srv, services.PermissionAuditLog)
	}

	if services.PermissionGroup != nil {
		adminv1.RegisterPermissionGroupServiceServer(srv, services.PermissionGroup)
	}

	if services.PolicyEvaluationLog != nil {
		adminv1.RegisterPolicyEvaluationLogServiceServer(srv, services.PolicyEvaluationLog)
	}

	if services.Position != nil {
		adminv1.RegisterPositionServiceServer(srv, services.Position)
	}

	if services.Role != nil {
		adminv1.RegisterRoleServiceServer(srv, services.Role)
	}

	if services.Task != nil {
		adminv1.RegisterTaskServiceServer(srv, services.Task)
	}

	if services.Tenant != nil {
		adminv1.RegisterTenantServiceServer(srv, services.Tenant)
	}

	if services.User != nil {
		adminv1.RegisterUserServiceServer(srv, services.User)
	}

}
