// Code generated by ent, DO NOT EDIT.

package ent

import (
	"admin/internal/data/ent/dictcategory"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 字典分类表
type DictCategory struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 是否启用
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 排序值（越小越靠前）
	SortOrder *uint32 `json:"sort_order,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 描述
	Description *string `json:"description,omitempty"`
	// 父节点ID
	ParentID *uint32 `json:"parent_id,omitempty"`
	// 树路径，规范： 根节点: /，非根节点: /1/2/3/（以 / 开头且以 / 结尾）。禁止空字符串（NULL 表示未设置）。
	Path *string `json:"path,omitempty"`
	// 分类稳定键，如 page、menu、prompt、user_management
	CategoryKey string `json:"category_key,omitempty"`
	// 分类显示名，后台默认展示名称
	CategoryName string `json:"category_name,omitempty"`
	// 分类层级
	CategoryLevel dictcategory.CategoryLevel `json:"category_level,omitempty"`
	// 分类场景
	Scene dictcategory.Scene `json:"scene,omitempty"`
	// 是否系统内置
	IsBuiltin bool `json:"is_builtin,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DictCategoryQuery when eager-loading is set.
	Edges        DictCategoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DictCategoryEdges holds the relations/edges for other nodes in the graph.
type DictCategoryEdges struct {
	// Parent holds the value of the parent edge.
	Parent *DictCategory `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*DictCategory `json:"children,omitempty"`
	// Labels holds the value of the labels edge.
	Labels []*DictLabel `json:"labels,omitempty"`
	// I18ns holds the value of the i18ns edge.
	I18ns []*DictCategoryI18n `json:"i18ns,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DictCategoryEdges) ParentOrErr() (*DictCategory, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dictcategory.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e DictCategoryEdges) ChildrenOrErr() ([]*DictCategory, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// LabelsOrErr returns the Labels value or an error if the edge
// was not loaded in eager-loading.
func (e DictCategoryEdges) LabelsOrErr() ([]*DictLabel, error) {
	if e.loadedTypes[2] {
		return e.Labels, nil
	}
	return nil, &NotLoadedError{edge: "labels"}
}

// I18nsOrErr returns the I18ns value or an error if the edge
// was not loaded in eager-loading.
func (e DictCategoryEdges) I18nsOrErr() ([]*DictCategoryI18n, error) {
	if e.loadedTypes[3] {
		return e.I18ns, nil
	}
	return nil, &NotLoadedError{edge: "i18ns"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DictCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dictcategory.FieldIsEnabled, dictcategory.FieldIsBuiltin:
			values[i] = new(sql.NullBool)
		case dictcategory.FieldID, dictcategory.FieldCreatedBy, dictcategory.FieldUpdatedBy, dictcategory.FieldDeletedBy, dictcategory.FieldSortOrder, dictcategory.FieldTenantID, dictcategory.FieldParentID:
			values[i] = new(sql.NullInt64)
		case dictcategory.FieldRemark, dictcategory.FieldDescription, dictcategory.FieldPath, dictcategory.FieldCategoryKey, dictcategory.FieldCategoryName, dictcategory.FieldCategoryLevel, dictcategory.FieldScene:
			values[i] = new(sql.NullString)
		case dictcategory.FieldCreatedAt, dictcategory.FieldUpdatedAt, dictcategory.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DictCategory fields.
func (_m *DictCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dictcategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case dictcategory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case dictcategory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case dictcategory.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case dictcategory.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case dictcategory.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case dictcategory.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case dictcategory.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = new(bool)
				*_m.IsEnabled = value.Bool
			}
		case dictcategory.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = new(uint32)
				*_m.SortOrder = uint32(value.Int64)
			}
		case dictcategory.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case dictcategory.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case dictcategory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case dictcategory.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(uint32)
				*_m.ParentID = uint32(value.Int64)
			}
		case dictcategory.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = new(string)
				*_m.Path = value.String
			}
		case dictcategory.FieldCategoryKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_key", values[i])
			} else if value.Valid {
				_m.CategoryKey = value.String
			}
		case dictcategory.FieldCategoryName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_name", values[i])
			} else if value.Valid {
				_m.CategoryName = value.String
			}
		case dictcategory.FieldCategoryLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_level", values[i])
			} else if value.Valid {
				_m.CategoryLevel = dictcategory.CategoryLevel(value.String)
			}
		case dictcategory.FieldScene:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scene", values[i])
			} else if value.Valid {
				_m.Scene = dictcategory.Scene(value.String)
			}
		case dictcategory.FieldIsBuiltin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_builtin", values[i])
			} else if value.Valid {
				_m.IsBuiltin = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DictCategory.
// This includes values selected through modifiers, order, etc.
func (_m *DictCategory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the DictCategory entity.
func (_m *DictCategory) QueryParent() *DictCategoryQuery {
	return NewDictCategoryClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the DictCategory entity.
func (_m *DictCategory) QueryChildren() *DictCategoryQuery {
	return NewDictCategoryClient(_m.config).QueryChildren(_m)
}

// QueryLabels queries the "labels" edge of the DictCategory entity.
func (_m *DictCategory) QueryLabels() *DictLabelQuery {
	return NewDictCategoryClient(_m.config).QueryLabels(_m)
}

// QueryI18ns queries the "i18ns" edge of the DictCategory entity.
func (_m *DictCategory) QueryI18ns() *DictCategoryI18nQuery {
	return NewDictCategoryClient(_m.config).QueryI18ns(_m)
}

// Update returns a builder for updating this DictCategory.
// Note that you need to call DictCategory.Unwrap() before calling this method if this DictCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DictCategory) Update() *DictCategoryUpdateOne {
	return NewDictCategoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DictCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DictCategory) Unwrap() *DictCategory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DictCategory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DictCategory) String() string {
	var builder strings.Builder
	builder.WriteString("DictCategory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsEnabled; v != nil {
		builder.WriteString("is_enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SortOrder; v != nil {
		builder.WriteString("sort_order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Path; v != nil {
		builder.WriteString("path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("category_key=")
	builder.WriteString(_m.CategoryKey)
	builder.WriteString(", ")
	builder.WriteString("category_name=")
	builder.WriteString(_m.CategoryName)
	builder.WriteString(", ")
	builder.WriteString("category_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.CategoryLevel))
	builder.WriteString(", ")
	builder.WriteString("scene=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scene))
	builder.WriteString(", ")
	builder.WriteString("is_builtin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsBuiltin))
	builder.WriteByte(')')
	return builder.String()
}

// DictCategories is a parsable slice of DictCategory.
type DictCategories []*DictCategory
