// Code generated by ent, DO NOT EDIT.

package ent

import (
	"admin/internal/data/ent/dictcategory"
	"admin/internal/data/ent/dictcategoryi18n"
	"admin/internal/data/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictCategoryI18nUpdate is the builder for updating DictCategoryI18n entities.
type DictCategoryI18nUpdate struct {
	config
	hooks     []Hook
	mutation  *DictCategoryI18nMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DictCategoryI18nUpdate builder.
func (_u *DictCategoryI18nUpdate) Where(ps ...predicate.DictCategoryI18n) *DictCategoryI18nUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictCategoryI18nUpdate) SetUpdatedAt(v time.Time) *DictCategoryI18nUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableUpdatedAt(v *time.Time) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictCategoryI18nUpdate) ClearUpdatedAt() *DictCategoryI18nUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictCategoryI18nUpdate) SetDeletedAt(v time.Time) *DictCategoryI18nUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableDeletedAt(v *time.Time) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictCategoryI18nUpdate) ClearDeletedAt() *DictCategoryI18nUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictCategoryI18nUpdate) SetCreatedBy(v uint32) *DictCategoryI18nUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableCreatedBy(v *uint32) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictCategoryI18nUpdate) AddCreatedBy(v int32) *DictCategoryI18nUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictCategoryI18nUpdate) ClearCreatedBy() *DictCategoryI18nUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictCategoryI18nUpdate) SetUpdatedBy(v uint32) *DictCategoryI18nUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableUpdatedBy(v *uint32) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictCategoryI18nUpdate) AddUpdatedBy(v int32) *DictCategoryI18nUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictCategoryI18nUpdate) ClearUpdatedBy() *DictCategoryI18nUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictCategoryI18nUpdate) SetDeletedBy(v uint32) *DictCategoryI18nUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableDeletedBy(v *uint32) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictCategoryI18nUpdate) AddDeletedBy(v int32) *DictCategoryI18nUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictCategoryI18nUpdate) ClearDeletedBy() *DictCategoryI18nUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictCategoryI18nUpdate) SetDescription(v string) *DictCategoryI18nUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableDescription(v *string) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DictCategoryI18nUpdate) ClearDescription() *DictCategoryI18nUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *DictCategoryI18nUpdate) SetCategoryID(v uint32) *DictCategoryI18nUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableCategoryID(v *uint32) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *DictCategoryI18nUpdate) SetDisplayName(v string) *DictCategoryI18nUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *DictCategoryI18nUpdate) SetNillableDisplayName(v *string) *DictCategoryI18nUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetCategory sets the "category" edge to the DictCategory entity.
func (_u *DictCategoryI18nUpdate) SetCategory(v *DictCategory) *DictCategoryI18nUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the DictCategoryI18nMutation object of the builder.
func (_u *DictCategoryI18nUpdate) Mutation() *DictCategoryI18nMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the DictCategory entity.
func (_u *DictCategoryI18nUpdate) ClearCategory() *DictCategoryI18nUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictCategoryI18nUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictCategoryI18nUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictCategoryI18nUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictCategoryI18nUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictCategoryI18nUpdate) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := dictcategoryi18n.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "DictCategoryI18n.display_name": %w`, err)}
		}
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DictCategoryI18n.category"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictCategoryI18nUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictCategoryI18nUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictCategoryI18nUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictcategoryi18n.Table, dictcategoryi18n.Columns, sqlgraph.NewFieldSpec(dictcategoryi18n.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dictcategoryi18n.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictcategoryi18n.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dictcategoryi18n.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictcategoryi18n.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictcategoryi18n.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dictcategoryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dictcategoryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dictcategoryi18n.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dictcategoryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dictcategoryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dictcategoryi18n.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dictcategoryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dictcategoryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dictcategoryi18n.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dictcategoryi18n.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dictcategoryi18n.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dictcategoryi18n.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(dictcategoryi18n.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictcategoryi18n.CategoryTable,
			Columns: []string{dictcategoryi18n.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictcategory.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictcategoryi18n.CategoryTable,
			Columns: []string{dictcategoryi18n.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictcategory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictcategoryi18n.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictCategoryI18nUpdateOne is the builder for updating a single DictCategoryI18n entity.
type DictCategoryI18nUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DictCategoryI18nMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictCategoryI18nUpdateOne) SetUpdatedAt(v time.Time) *DictCategoryI18nUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableUpdatedAt(v *time.Time) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictCategoryI18nUpdateOne) ClearUpdatedAt() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictCategoryI18nUpdateOne) SetDeletedAt(v time.Time) *DictCategoryI18nUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableDeletedAt(v *time.Time) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictCategoryI18nUpdateOne) ClearDeletedAt() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictCategoryI18nUpdateOne) SetCreatedBy(v uint32) *DictCategoryI18nUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableCreatedBy(v *uint32) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictCategoryI18nUpdateOne) AddCreatedBy(v int32) *DictCategoryI18nUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictCategoryI18nUpdateOne) ClearCreatedBy() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictCategoryI18nUpdateOne) SetUpdatedBy(v uint32) *DictCategoryI18nUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableUpdatedBy(v *uint32) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictCategoryI18nUpdateOne) AddUpdatedBy(v int32) *DictCategoryI18nUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictCategoryI18nUpdateOne) ClearUpdatedBy() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictCategoryI18nUpdateOne) SetDeletedBy(v uint32) *DictCategoryI18nUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableDeletedBy(v *uint32) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictCategoryI18nUpdateOne) AddDeletedBy(v int32) *DictCategoryI18nUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictCategoryI18nUpdateOne) ClearDeletedBy() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictCategoryI18nUpdateOne) SetDescription(v string) *DictCategoryI18nUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableDescription(v *string) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DictCategoryI18nUpdateOne) ClearDescription() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *DictCategoryI18nUpdateOne) SetCategoryID(v uint32) *DictCategoryI18nUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableCategoryID(v *uint32) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *DictCategoryI18nUpdateOne) SetDisplayName(v string) *DictCategoryI18nUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *DictCategoryI18nUpdateOne) SetNillableDisplayName(v *string) *DictCategoryI18nUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetCategory sets the "category" edge to the DictCategory entity.
func (_u *DictCategoryI18nUpdateOne) SetCategory(v *DictCategory) *DictCategoryI18nUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the DictCategoryI18nMutation object of the builder.
func (_u *DictCategoryI18nUpdateOne) Mutation() *DictCategoryI18nMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the DictCategory entity.
func (_u *DictCategoryI18nUpdateOne) ClearCategory() *DictCategoryI18nUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the DictCategoryI18nUpdate builder.
func (_u *DictCategoryI18nUpdateOne) Where(ps ...predicate.DictCategoryI18n) *DictCategoryI18nUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictCategoryI18nUpdateOne) Select(field string, fields ...string) *DictCategoryI18nUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictCategoryI18n entity.
func (_u *DictCategoryI18nUpdateOne) Save(ctx context.Context) (*DictCategoryI18n, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictCategoryI18nUpdateOne) SaveX(ctx context.Context) *DictCategoryI18n {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictCategoryI18nUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictCategoryI18nUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictCategoryI18nUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := dictcategoryi18n.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "DictCategoryI18n.display_name": %w`, err)}
		}
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DictCategoryI18n.category"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictCategoryI18nUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictCategoryI18nUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictCategoryI18nUpdateOne) sqlSave(ctx context.Context) (_node *DictCategoryI18n, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictcategoryi18n.Table, dictcategoryi18n.Columns, sqlgraph.NewFieldSpec(dictcategoryi18n.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictCategoryI18n.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictcategoryi18n.FieldID)
		for _, f := range fields {
			if !dictcategoryi18n.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictcategoryi18n.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dictcategoryi18n.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictcategoryi18n.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dictcategoryi18n.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictcategoryi18n.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictcategoryi18n.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dictcategoryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dictcategoryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dictcategoryi18n.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dictcategoryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dictcategoryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dictcategoryi18n.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dictcategoryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dictcategoryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dictcategoryi18n.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dictcategoryi18n.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dictcategoryi18n.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(dictcategoryi18n.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(dictcategoryi18n.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictcategoryi18n.CategoryTable,
			Columns: []string{dictcategoryi18n.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictcategory.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictcategoryi18n.CategoryTable,
			Columns: []string{dictcategoryi18n.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictcategory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DictCategoryI18n{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictcategoryi18n.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
