// Code generated by ent, DO NOT EDIT.

package ent

import (
	"admin/internal/data/ent/tasklog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskLogCreate is the builder for creating a TaskLog entity.
type TaskLogCreate struct {
	config
	mutation *TaskLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *TaskLogCreate) SetTenantID(v uint32) *TaskLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableTenantID(v *uint32) *TaskLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *TaskLogCreate) SetTaskID(v uint64) *TaskLogCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableTaskID(v *uint64) *TaskLogCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetInput sets the "input" field.
func (_c *TaskLogCreate) SetInput(v string) *TaskLogCreate {
	_c.mutation.SetInput(v)
	return _c
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableInput(v *string) *TaskLogCreate {
	if v != nil {
		_c.SetInput(*v)
	}
	return _c
}

// SetOutput sets the "output" field.
func (_c *TaskLogCreate) SetOutput(v string) *TaskLogCreate {
	_c.mutation.SetOutput(v)
	return _c
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableOutput(v *string) *TaskLogCreate {
	if v != nil {
		_c.SetOutput(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *TaskLogCreate) SetError(v string) *TaskLogCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableError(v *string) *TaskLogCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TaskLogCreate) SetStatus(v tasklog.Status) *TaskLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableStatus(v *tasklog.Status) *TaskLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProcessTime sets the "process_time" field.
func (_c *TaskLogCreate) SetProcessTime(v uint32) *TaskLogCreate {
	_c.mutation.SetProcessTime(v)
	return _c
}

// SetNillableProcessTime sets the "process_time" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableProcessTime(v *uint32) *TaskLogCreate {
	if v != nil {
		_c.SetProcessTime(*v)
	}
	return _c
}

// SetExecuteTime sets the "execute_time" field.
func (_c *TaskLogCreate) SetExecuteTime(v time.Time) *TaskLogCreate {
	_c.mutation.SetExecuteTime(v)
	return _c
}

// SetNillableExecuteTime sets the "execute_time" field if the given value is not nil.
func (_c *TaskLogCreate) SetNillableExecuteTime(v *time.Time) *TaskLogCreate {
	if v != nil {
		_c.SetExecuteTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskLogCreate) SetID(v uint64) *TaskLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TaskLogMutation object of the builder.
func (_c *TaskLogCreate) Mutation() *TaskLogMutation {
	return _c.mutation
}

// Save creates the TaskLog in the database.
func (_c *TaskLogCreate) Save(ctx context.Context) (*TaskLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskLogCreate) SaveX(ctx context.Context) *TaskLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskLogCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := tasklog.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tasklog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskLogCreate) check() error {
	if v, ok := _c.mutation.Input(); ok {
		if err := tasklog.InputValidator(v); err != nil {
			return &ValidationError{Name: "input", err: fmt.Errorf(`ent: validator failed for field "TaskLog.input": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TaskLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := tasklog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskLog.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tasklog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TaskLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TaskLogCreate) sqlSave(ctx context.Context) (*TaskLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskLogCreate) createSpec() (*TaskLog, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tasklog.Table, sqlgraph.NewFieldSpec(tasklog.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tasklog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(tasklog.FieldTaskID, field.TypeUint64, value)
		_node.TaskID = &value
	}
	if value, ok := _c.mutation.Input(); ok {
		_spec.SetField(tasklog.FieldInput, field.TypeString, value)
		_node.Input = &value
	}
	if value, ok := _c.mutation.Output(); ok {
		_spec.SetField(tasklog.FieldOutput, field.TypeString, value)
		_node.Output = &value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(tasklog.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tasklog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProcessTime(); ok {
		_spec.SetField(tasklog.FieldProcessTime, field.TypeUint32, value)
		_node.ProcessTime = &value
	}
	if value, ok := _c.mutation.ExecuteTime(); ok {
		_spec.SetField(tasklog.FieldExecuteTime, field.TypeTime, value)
		_node.ExecuteTime = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskLog.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskLogUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskLogCreate) OnConflict(opts ...sql.ConflictOption) *TaskLogUpsertOne {
	_c.conflict = opts
	return &TaskLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskLogCreate) OnConflictColumns(columns ...string) *TaskLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskLogUpsertOne{
		create: _c,
	}
}

type (
	// TaskLogUpsertOne is the builder for "upsert"-ing
	//  one TaskLog node.
	TaskLogUpsertOne struct {
		create *TaskLogCreate
	}

	// TaskLogUpsert is the "OnConflict" setter.
	TaskLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskID sets the "task_id" field.
func (u *TaskLogUpsert) SetTaskID(v uint64) *TaskLogUpsert {
	u.Set(tasklog.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateTaskID() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldTaskID)
	return u
}

// AddTaskID adds v to the "task_id" field.
func (u *TaskLogUpsert) AddTaskID(v uint64) *TaskLogUpsert {
	u.Add(tasklog.FieldTaskID, v)
	return u
}

// ClearTaskID clears the value of the "task_id" field.
func (u *TaskLogUpsert) ClearTaskID() *TaskLogUpsert {
	u.SetNull(tasklog.FieldTaskID)
	return u
}

// SetInput sets the "input" field.
func (u *TaskLogUpsert) SetInput(v string) *TaskLogUpsert {
	u.Set(tasklog.FieldInput, v)
	return u
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateInput() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldInput)
	return u
}

// ClearInput clears the value of the "input" field.
func (u *TaskLogUpsert) ClearInput() *TaskLogUpsert {
	u.SetNull(tasklog.FieldInput)
	return u
}

// SetOutput sets the "output" field.
func (u *TaskLogUpsert) SetOutput(v string) *TaskLogUpsert {
	u.Set(tasklog.FieldOutput, v)
	return u
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateOutput() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldOutput)
	return u
}

// ClearOutput clears the value of the "output" field.
func (u *TaskLogUpsert) ClearOutput() *TaskLogUpsert {
	u.SetNull(tasklog.FieldOutput)
	return u
}

// SetError sets the "error" field.
func (u *TaskLogUpsert) SetError(v string) *TaskLogUpsert {
	u.Set(tasklog.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateError() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *TaskLogUpsert) ClearError() *TaskLogUpsert {
	u.SetNull(tasklog.FieldError)
	return u
}

// SetStatus sets the "status" field.
func (u *TaskLogUpsert) SetStatus(v tasklog.Status) *TaskLogUpsert {
	u.Set(tasklog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateStatus() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldStatus)
	return u
}

// SetProcessTime sets the "process_time" field.
func (u *TaskLogUpsert) SetProcessTime(v uint32) *TaskLogUpsert {
	u.Set(tasklog.FieldProcessTime, v)
	return u
}

// UpdateProcessTime sets the "process_time" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateProcessTime() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldProcessTime)
	return u
}

// AddProcessTime adds v to the "process_time" field.
func (u *TaskLogUpsert) AddProcessTime(v uint32) *TaskLogUpsert {
	u.Add(tasklog.FieldProcessTime, v)
	return u
}

// ClearProcessTime clears the value of the "process_time" field.
func (u *TaskLogUpsert) ClearProcessTime() *TaskLogUpsert {
	u.SetNull(tasklog.FieldProcessTime)
	return u
}

// SetExecuteTime sets the "execute_time" field.
func (u *TaskLogUpsert) SetExecuteTime(v time.Time) *TaskLogUpsert {
	u.Set(tasklog.FieldExecuteTime, v)
	return u
}

// UpdateExecuteTime sets the "execute_time" field to the value that was provided on create.
func (u *TaskLogUpsert) UpdateExecuteTime() *TaskLogUpsert {
	u.SetExcluded(tasklog.FieldExecuteTime)
	return u
}

// ClearExecuteTime clears the value of the "execute_time" field.
func (u *TaskLogUpsert) ClearExecuteTime() *TaskLogUpsert {
	u.SetNull(tasklog.FieldExecuteTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tasklog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskLogUpsertOne) UpdateNewValues() *TaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tasklog.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(tasklog.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskLogUpsertOne) Ignore() *TaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskLogUpsertOne) DoNothing() *TaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskLogCreate.OnConflict
// documentation for more info.
func (u *TaskLogUpsertOne) Update(set func(*TaskLogUpsert)) *TaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskLogUpsertOne) SetTaskID(v uint64) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *TaskLogUpsertOne) AddTaskID(v uint64) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateTaskID() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateTaskID()
	})
}

// ClearTaskID clears the value of the "task_id" field.
func (u *TaskLogUpsertOne) ClearTaskID() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearTaskID()
	})
}

// SetInput sets the "input" field.
func (u *TaskLogUpsertOne) SetInput(v string) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetInput(v)
	})
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateInput() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateInput()
	})
}

// ClearInput clears the value of the "input" field.
func (u *TaskLogUpsertOne) ClearInput() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearInput()
	})
}

// SetOutput sets the "output" field.
func (u *TaskLogUpsertOne) SetOutput(v string) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateOutput() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *TaskLogUpsertOne) ClearOutput() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearOutput()
	})
}

// SetError sets the "error" field.
func (u *TaskLogUpsertOne) SetError(v string) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateError() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *TaskLogUpsertOne) ClearError() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearError()
	})
}

// SetStatus sets the "status" field.
func (u *TaskLogUpsertOne) SetStatus(v tasklog.Status) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateStatus() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateStatus()
	})
}

// SetProcessTime sets the "process_time" field.
func (u *TaskLogUpsertOne) SetProcessTime(v uint32) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetProcessTime(v)
	})
}

// AddProcessTime adds v to the "process_time" field.
func (u *TaskLogUpsertOne) AddProcessTime(v uint32) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.AddProcessTime(v)
	})
}

// UpdateProcessTime sets the "process_time" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateProcessTime() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateProcessTime()
	})
}

// ClearProcessTime clears the value of the "process_time" field.
func (u *TaskLogUpsertOne) ClearProcessTime() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearProcessTime()
	})
}

// SetExecuteTime sets the "execute_time" field.
func (u *TaskLogUpsertOne) SetExecuteTime(v time.Time) *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetExecuteTime(v)
	})
}

// UpdateExecuteTime sets the "execute_time" field to the value that was provided on create.
func (u *TaskLogUpsertOne) UpdateExecuteTime() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateExecuteTime()
	})
}

// ClearExecuteTime clears the value of the "execute_time" field.
func (u *TaskLogUpsertOne) ClearExecuteTime() *TaskLogUpsertOne {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearExecuteTime()
	})
}

// Exec executes the query.
func (u *TaskLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskLogUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskLogUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskLogCreateBulk is the builder for creating many TaskLog entities in bulk.
type TaskLogCreateBulk struct {
	config
	err      error
	builders []*TaskLogCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskLog entities in the database.
func (_c *TaskLogCreateBulk) Save(ctx context.Context) ([]*TaskLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskLogCreateBulk) SaveX(ctx context.Context) []*TaskLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskLogUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskLogUpsertBulk {
	_c.conflict = opts
	return &TaskLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskLogCreateBulk) OnConflictColumns(columns ...string) *TaskLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskLogUpsertBulk{
		create: _c,
	}
}

// TaskLogUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskLog nodes.
type TaskLogUpsertBulk struct {
	create *TaskLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tasklog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskLogUpsertBulk) UpdateNewValues() *TaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tasklog.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(tasklog.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskLogUpsertBulk) Ignore() *TaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskLogUpsertBulk) DoNothing() *TaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskLogCreateBulk.OnConflict
// documentation for more info.
func (u *TaskLogUpsertBulk) Update(set func(*TaskLogUpsert)) *TaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskLogUpsertBulk) SetTaskID(v uint64) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *TaskLogUpsertBulk) AddTaskID(v uint64) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateTaskID() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateTaskID()
	})
}

// ClearTaskID clears the value of the "task_id" field.
func (u *TaskLogUpsertBulk) ClearTaskID() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearTaskID()
	})
}

// SetInput sets the "input" field.
func (u *TaskLogUpsertBulk) SetInput(v string) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetInput(v)
	})
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateInput() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateInput()
	})
}

// ClearInput clears the value of the "input" field.
func (u *TaskLogUpsertBulk) ClearInput() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearInput()
	})
}

// SetOutput sets the "output" field.
func (u *TaskLogUpsertBulk) SetOutput(v string) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateOutput() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *TaskLogUpsertBulk) ClearOutput() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearOutput()
	})
}

// SetError sets the "error" field.
func (u *TaskLogUpsertBulk) SetError(v string) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateError() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *TaskLogUpsertBulk) ClearError() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearError()
	})
}

// SetStatus sets the "status" field.
func (u *TaskLogUpsertBulk) SetStatus(v tasklog.Status) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateStatus() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateStatus()
	})
}

// SetProcessTime sets the "process_time" field.
func (u *TaskLogUpsertBulk) SetProcessTime(v uint32) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetProcessTime(v)
	})
}

// AddProcessTime adds v to the "process_time" field.
func (u *TaskLogUpsertBulk) AddProcessTime(v uint32) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.AddProcessTime(v)
	})
}

// UpdateProcessTime sets the "process_time" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateProcessTime() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateProcessTime()
	})
}

// ClearProcessTime clears the value of the "process_time" field.
func (u *TaskLogUpsertBulk) ClearProcessTime() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearProcessTime()
	})
}

// SetExecuteTime sets the "execute_time" field.
func (u *TaskLogUpsertBulk) SetExecuteTime(v time.Time) *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.SetExecuteTime(v)
	})
}

// UpdateExecuteTime sets the "execute_time" field to the value that was provided on create.
func (u *TaskLogUpsertBulk) UpdateExecuteTime() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.UpdateExecuteTime()
	})
}

// ClearExecuteTime clears the value of the "execute_time" field.
func (u *TaskLogUpsertBulk) ClearExecuteTime() *TaskLogUpsertBulk {
	return u.Update(func(s *TaskLogUpsert) {
		s.ClearExecuteTime()
	})
}

// Exec executes the query.
func (u *TaskLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
