// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-05-30 20:54:38 CST

package bootstrap

import (
	"admin/internal/data/repo"
	"github.com/chnxq/xkitpkg/app"
)

func (data *GeneratedData) GetAppCtx() *app.AppCtx {
	if data == nil {
		return nil
	}
	return data.AppContext
}

func (data *GeneratedData) ApiRepoProvider() repo.ApiRepo {
	if data == nil {
		return nil
	}
	return data.ApiRepo
}
func (data *GeneratedData) ApiAuditLogRepoProvider() repo.ApiAuditLogRepo {
	if data == nil {
		return nil
	}
	return data.ApiAuditLogRepo
}
func (data *GeneratedData) DataAccessAuditLogRepoProvider() repo.DataAccessAuditLogRepo {
	if data == nil {
		return nil
	}
	return data.DataAccessAuditLogRepo
}
func (data *GeneratedData) DictCategoryRepoProvider() repo.DictCategoryRepo {
	if data == nil {
		return nil
	}
	return data.DictCategoryRepo
}
func (data *GeneratedData) DictLabelRepoProvider() repo.DictLabelRepo {
	if data == nil {
		return nil
	}
	return data.DictLabelRepo
}
func (data *GeneratedData) DictLabelI18nRepoProvider() repo.DictLabelI18nRepo {
	if data == nil {
		return nil
	}
	return data.DictLabelI18nRepo
}
func (data *GeneratedData) FileRepoProvider() repo.FileRepo {
	if data == nil {
		return nil
	}
	return data.FileRepo
}
func (data *GeneratedData) InternalMessageRepoProvider() repo.InternalMessageRepo {
	if data == nil {
		return nil
	}
	return data.InternalMessageRepo
}
func (data *GeneratedData) InternalMessageRecipientRepoProvider() repo.InternalMessageRecipientRepo {
	if data == nil {
		return nil
	}
	return data.InternalMessageRecipientRepo
}
func (data *GeneratedData) InternalMessageCategoryRepoProvider() repo.InternalMessageCategoryRepo {
	if data == nil {
		return nil
	}
	return data.InternalMessageCategoryRepo
}
func (data *GeneratedData) LanguageRepoProvider() repo.LanguageRepo {
	if data == nil {
		return nil
	}
	return data.LanguageRepo
}
func (data *GeneratedData) LoginAuditLogRepoProvider() repo.LoginAuditLogRepo {
	if data == nil {
		return nil
	}
	return data.LoginAuditLogRepo
}
func (data *GeneratedData) LoginPolicyRepoProvider() repo.LoginPolicyRepo {
	if data == nil {
		return nil
	}
	return data.LoginPolicyRepo
}
func (data *GeneratedData) MenuRepoProvider() repo.MenuRepo {
	if data == nil {
		return nil
	}
	return data.MenuRepo
}
func (data *GeneratedData) OperationAuditLogRepoProvider() repo.OperationAuditLogRepo {
	if data == nil {
		return nil
	}
	return data.OperationAuditLogRepo
}
func (data *GeneratedData) OrgUnitRepoProvider() repo.OrgUnitRepo {
	if data == nil {
		return nil
	}
	return data.OrgUnitRepo
}
func (data *GeneratedData) PermissionRepoProvider() repo.PermissionRepo {
	if data == nil {
		return nil
	}
	return data.PermissionRepo
}
func (data *GeneratedData) PermissionGroupRepoProvider() repo.PermissionGroupRepo {
	if data == nil {
		return nil
	}
	return data.PermissionGroupRepo
}
func (data *GeneratedData) PermissionAuditLogRepoProvider() repo.PermissionAuditLogRepo {
	if data == nil {
		return nil
	}
	return data.PermissionAuditLogRepo
}
func (data *GeneratedData) PolicyEvaluationLogRepoProvider() repo.PolicyEvaluationLogRepo {
	if data == nil {
		return nil
	}
	return data.PolicyEvaluationLogRepo
}
func (data *GeneratedData) PositionRepoProvider() repo.PositionRepo {
	if data == nil {
		return nil
	}
	return data.PositionRepo
}
func (data *GeneratedData) RoleRepoProvider() repo.RoleRepo {
	if data == nil {
		return nil
	}
	return data.RoleRepo
}
func (data *GeneratedData) TaskRepoProvider() repo.TaskRepo {
	if data == nil {
		return nil
	}
	return data.TaskRepo
}
func (data *GeneratedData) TenantRepoProvider() repo.TenantRepo {
	if data == nil {
		return nil
	}
	return data.TenantRepo
}
func (data *GeneratedData) UserRepoProvider() repo.UserRepo {
	if data == nil {
		return nil
	}
	return data.UserRepo
}
func (data *GeneratedData) UserCredentialRepoProvider() repo.UserCredentialRepo {
	if data == nil {
		return nil
	}
	return data.UserCredentialRepo
}
