// Code generated by xkit.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 22:51:12 CST

package bootstrap

// Add GeneratedData/GeneratedServices bootstrap hooks here.
// This file is created once and is never overwritten by xkit.

func (data *GeneratedData) afterInit() {
	if data == nil {
		return
	}
	data.WrapAuditLogRepos()
}

func (services *GeneratedServices) afterInit(data *GeneratedData) {
	_, _ = services, data
}
