// Code generated by codex.
// generated at: 2026-05-30 20:54:37 CST

package service

// TODO: add FileService-specific hooks, helpers, and hand-written business logic here.
// Add FileService-specific hooks and helpers here.
// This file is created once and is never overwritten by xkit.
