// Code generated by xkit.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 23:51:21 CST

package service

import (
	"context"
	"fmt"

	v11 "admin/api/gen/internal_message/v1"
	"admin/internal/data/repo"
	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	crudviewer "github.com/chnxq/x-crud/viewer"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// TODO: add InternalMessageRecipientService-specific hooks, helpers, and hand-written business logic here.
// Add InternalMessageRecipientService-specific hooks and helpers here.
// This file is created once and is never overwritten by xkit.

// Keep this file for future non-generated extension logic.

func (s *InternalMessageRecipientService) listUserInboxImpl(ctx context.Context, req *paginationv1.PagingRequest) (*v11.ListUserInboxResponse, error) {
	if s == nil {
		return nil, fmt.Errorf("internal message recipient service is not initialized")
	}
	if s.internalMessageRecipientRepo == nil {
		s.log.Errorf("list user inbox failed: internal message recipient repo is not initialized")
		return nil, fmt.Errorf("internal message recipient repo is not initialized")
	}
	userID, err := currentInboxUserID(ctx, 0)
	if err != nil {
		s.log.Errorf("list user inbox failed: resolve current user: %s", err.Error())
		return nil, err
	}
	if req == nil {
		req = &paginationv1.PagingRequest{}
	}
	pageSize := int(req.GetPageSize())
	if pageSize == 0 {
		pageSize = int(req.GetLimit())
	}
	offset := int(req.GetOffset())
	if offset == 0 && req.GetPage() > 1 && pageSize > 0 {
		offset = int((req.GetPage() - 1) * req.GetPageSize())
	}
	resp, err := s.internalMessageRecipientRepo.ListUserInbox(ctx, userID, repo.InboxPagingRequest{
		Limit:  pageSize,
		Offset: offset,
	})
	if err != nil {
		s.log.Errorf("list user inbox failed: user_id=%d limit=%d offset=%d: %s", userID, pageSize, offset, err.Error())
		return nil, err
	}
	return resp, nil
}

func (s *InternalMessageRecipientService) deleteNotificationFromInboxImpl(ctx context.Context, req *v11.DeleteNotificationFromInboxRequest) (*emptypb.Empty, error) {
	if s == nil {
		return nil, fmt.Errorf("internal message recipient service is not initialized")
	}
	if s.internalMessageRecipientRepo == nil {
		s.log.Errorf("delete notification from inbox failed: internal message recipient repo is not initialized")
		return nil, fmt.Errorf("internal message recipient repo is not initialized")
	}
	if req == nil {
		return nil, v11.ErrorBadRequest("request is required")
	}
	userID, err := currentInboxUserID(ctx, req.GetUserId())
	if err != nil {
		s.log.Errorf("delete notification from inbox failed: resolve current user requested_user_id=%d: %s", req.GetUserId(), err.Error())
		return nil, err
	}
	if err := s.internalMessageRecipientRepo.DeleteFromInbox(ctx, userID, req.GetRecipientIds()); err != nil {
		s.log.Errorf("delete notification from inbox failed: user_id=%d recipient_ids=%v: %s", userID, req.GetRecipientIds(), err.Error())
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func (s *InternalMessageRecipientService) markNotificationAsReadImpl(ctx context.Context, req *v11.MarkNotificationAsReadRequest) (*emptypb.Empty, error) {
	if s == nil {
		return nil, fmt.Errorf("internal message recipient service is not initialized")
	}
	if s.internalMessageRecipientRepo == nil {
		s.log.Errorf("mark notification as read failed: internal message recipient repo is not initialized")
		return nil, fmt.Errorf("internal message recipient repo is not initialized")
	}
	if req == nil {
		return nil, v11.ErrorBadRequest("request is required")
	}
	userID, err := currentInboxUserID(ctx, req.GetUserId())
	if err != nil {
		s.log.Errorf("mark notification as read failed: resolve current user requested_user_id=%d: %s", req.GetUserId(), err.Error())
		return nil, err
	}
	if err := s.internalMessageRecipientRepo.MarkAsRead(ctx, userID, req.GetRecipientIds()); err != nil {
		s.log.Errorf("mark notification as read failed: user_id=%d recipient_ids=%v: %s", userID, req.GetRecipientIds(), err.Error())
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func currentInboxUserID(ctx context.Context, requested uint32) (uint32, error) {
	if requested != 0 {
		return requested, nil
	}
	viewer, ok := crudviewer.FromContext(ctx)
	if !ok || viewer == nil || viewer.UserID() == 0 {
		return 0, v11.ErrorBadRequest("user id is required")
	}
	return uint32(viewer.UserID()), nil
}
