// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-05-30 20:54:37 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/dict/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type LanguageService struct {
	adminv1.LanguageServiceHTTPServer
	adminv1.UnimplementedLanguageServiceServer

	log *log.Helper

	languageRepo repo.LanguageRepo
}

func NewLanguageService(ctx *app.AppCtx, languageRepo repo.LanguageRepo) *LanguageService {
	return &LanguageService{
		log:          ctx.NewLoggerHelper("language/service"),
		languageRepo: languageRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *LanguageService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListLanguageResponse, error) {
	return s.languageRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *LanguageService) Get(ctx context.Context, req *v11.GetLanguageRequest) (*v11.Language, error) {
	return s.languageRepo.Get(ctx, req)
}

// Create is generated from the source proto contract.
// Classification: standard.
func (s *LanguageService) Create(ctx context.Context, req *v11.CreateLanguageRequest) (*emptypb.Empty, error) {
	return s.languageRepo.Create(ctx, req)
}

// Update is generated from the source proto contract.
// Classification: standard.
func (s *LanguageService) Update(ctx context.Context, req *v11.UpdateLanguageRequest) (*emptypb.Empty, error) {
	return s.languageRepo.Update(ctx, req)
}

// Delete is generated from the source proto contract.
// Classification: standard.
func (s *LanguageService) Delete(ctx context.Context, req *v11.DeleteLanguageRequest) (*emptypb.Empty, error) {
	return s.languageRepo.Delete(ctx, req)
}

// BatchCreate is generated from the source proto contract.
// Classification: semi-standard.
func (s *LanguageService) BatchCreate(ctx context.Context, req *v11.BatchCreateLanguagesRequest) (*emptypb.Empty, error) {
	_ = ctx
	_ = req

	// TODO: implement LanguageService.BatchCreate business logic manually or move it to a manual extension.
	return &emptypb.Empty{}, nil
}
