// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.1.0
// generated at: 2026-05-25 16:34:37 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/authentication/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type LoginPolicyService struct {
	adminv1.LoginPolicyServiceHTTPServer
	adminv1.UnimplementedLoginPolicyServiceServer

	log *log.Helper

	loginPolicyRepo repo.LoginPolicyRepo
}

func NewLoginPolicyService(ctx *app.AppCtx, loginPolicyRepo repo.LoginPolicyRepo) *LoginPolicyService {
	return &LoginPolicyService{
		log:             ctx.NewLoggerHelper("login_policy/service"),
		loginPolicyRepo: loginPolicyRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *LoginPolicyService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListLoginPolicyResponse, error) {
	return s.loginPolicyRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *LoginPolicyService) Get(ctx context.Context, req *v11.GetLoginPolicyRequest) (*v11.LoginPolicy, error) {
	return s.loginPolicyRepo.Get(ctx, req)
}

// Create is generated from the source proto contract.
// Classification: standard.
func (s *LoginPolicyService) Create(ctx context.Context, req *v11.CreateLoginPolicyRequest) (*emptypb.Empty, error) {
	return s.loginPolicyRepo.Create(ctx, req)
}

// Update is generated from the source proto contract.
// Classification: standard.
func (s *LoginPolicyService) Update(ctx context.Context, req *v11.UpdateLoginPolicyRequest) (*emptypb.Empty, error) {
	return s.loginPolicyRepo.Update(ctx, req)
}

// Delete is generated from the source proto contract.
// Classification: standard.
func (s *LoginPolicyService) Delete(ctx context.Context, req *v11.DeleteLoginPolicyRequest) (*emptypb.Empty, error) {
	return s.loginPolicyRepo.Delete(ctx, req)
}
