// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.1.0
// generated at: 2026-05-25 16:34:37 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/identity/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type OrgUnitService struct {
	adminv1.OrgUnitServiceHTTPServer
	adminv1.UnimplementedOrgUnitServiceServer

	log *log.Helper

	orgUnitRepo repo.OrgUnitRepo
}

func NewOrgUnitService(ctx *app.AppCtx, orgUnitRepo repo.OrgUnitRepo) *OrgUnitService {
	return &OrgUnitService{
		log:         ctx.NewLoggerHelper("org_unit/service"),
		orgUnitRepo: orgUnitRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *OrgUnitService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListOrgUnitResponse, error) {
	return s.orgUnitRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *OrgUnitService) Get(ctx context.Context, req *v11.GetOrgUnitRequest) (*v11.OrgUnit, error) {
	return s.orgUnitRepo.Get(ctx, req)
}

// Create is generated from the source proto contract.
// Classification: standard.
func (s *OrgUnitService) Create(ctx context.Context, req *v11.CreateOrgUnitRequest) (*emptypb.Empty, error) {
	return s.orgUnitRepo.Create(ctx, req)
}

// Update is generated from the source proto contract.
// Classification: standard.
func (s *OrgUnitService) Update(ctx context.Context, req *v11.UpdateOrgUnitRequest) (*emptypb.Empty, error) {
	return s.orgUnitRepo.Update(ctx, req)
}

// Delete is generated from the source proto contract.
// Classification: standard.
func (s *OrgUnitService) Delete(ctx context.Context, req *v11.DeleteOrgUnitRequest) (*emptypb.Empty, error) {
	return s.orgUnitRepo.Delete(ctx, req)
}
