// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.1.0
// generated at: 2026-05-25 16:34:37 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/audit/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
)

type PermissionAuditLogService struct {
	adminv1.PermissionAuditLogServiceHTTPServer
	adminv1.UnimplementedPermissionAuditLogServiceServer

	log *log.Helper

	permissionAuditLogRepo repo.PermissionAuditLogRepo
}

func NewPermissionAuditLogService(ctx *app.AppCtx, permissionAuditLogRepo repo.PermissionAuditLogRepo) *PermissionAuditLogService {
	return &PermissionAuditLogService{
		log:                    ctx.NewLoggerHelper("permission_audit_log/service"),
		permissionAuditLogRepo: permissionAuditLogRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *PermissionAuditLogService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListPermissionAuditLogResponse, error) {
	return s.permissionAuditLogRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *PermissionAuditLogService) Get(ctx context.Context, req *v11.GetPermissionAuditLogRequest) (*v11.PermissionAuditLog, error) {
	return s.permissionAuditLogRepo.Get(ctx, req)
}
