// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.1.0
// generated at: 2026-05-25 16:34:37 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/permission/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type RoleService struct {
	adminv1.RoleServiceHTTPServer
	adminv1.UnimplementedRoleServiceServer

	log *log.Helper

	roleRepo repo.RoleRepo
}

func NewRoleService(ctx *app.AppCtx, roleRepo repo.RoleRepo) *RoleService {
	return &RoleService{
		log:      ctx.NewLoggerHelper("role/service"),
		roleRepo: roleRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *RoleService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListRoleResponse, error) {
	return s.roleRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *RoleService) Get(ctx context.Context, req *v11.GetRoleRequest) (*v11.Role, error) {
	return s.roleRepo.Get(ctx, req)
}

// Create is generated from the source proto contract.
// Classification: standard.
func (s *RoleService) Create(ctx context.Context, req *v11.CreateRoleRequest) (*emptypb.Empty, error) {
	return s.roleRepo.Create(ctx, req)
}

// Update is generated from the source proto contract.
// Classification: standard.
func (s *RoleService) Update(ctx context.Context, req *v11.UpdateRoleRequest) (*emptypb.Empty, error) {
	return s.roleRepo.Update(ctx, req)
}

// Delete is generated from the source proto contract.
// Classification: standard.
func (s *RoleService) Delete(ctx context.Context, req *v11.DeleteRoleRequest) (*emptypb.Empty, error) {
	return s.roleRepo.Delete(ctx, req)
}
