// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 18:29:59 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/task/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type TaskGroupService struct {
	adminv1.TaskGroupServiceHTTPServer
	adminv1.UnimplementedTaskGroupServiceServer

	log *log.Helper

	taskGroupRepo repo.TaskGroupRepo
}

func NewTaskGroupService(ctx *app.AppCtx, taskGroupRepo repo.TaskGroupRepo) *TaskGroupService {
	return &TaskGroupService{
		log:           ctx.NewLoggerHelper("task_group/service"),
		taskGroupRepo: taskGroupRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *TaskGroupService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListTaskGroupResponse, error) {
	return s.taskGroupRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *TaskGroupService) Get(ctx context.Context, req *v11.GetTaskGroupRequest) (*v11.TaskGroup, error) {
	return s.taskGroupRepo.Get(ctx, req)
}

// Create is generated from the source proto contract.
// Classification: standard.
func (s *TaskGroupService) Create(ctx context.Context, req *v11.CreateTaskGroupRequest) (*emptypb.Empty, error) {
	return s.taskGroupRepo.Create(ctx, req)
}

// Update is generated from the source proto contract.
// Classification: standard.
func (s *TaskGroupService) Update(ctx context.Context, req *v11.UpdateTaskGroupRequest) (*emptypb.Empty, error) {
	return s.taskGroupRepo.Update(ctx, req)
}

// Delete is generated from the source proto contract.
// Classification: standard.
func (s *TaskGroupService) Delete(ctx context.Context, req *v11.DeleteTaskGroupRequest) (*emptypb.Empty, error) {
	return s.taskGroupRepo.Delete(ctx, req)
}

// Start is generated from the source proto contract.
// Classification: special.
func (s *TaskGroupService) Start(ctx context.Context, req *v11.StartTaskGroupRequest) (*emptypb.Empty, error) {
	_ = ctx
	_ = req

	// TODO: implement TaskGroupService.Start business logic manually or move it to a manual extension.
	return &emptypb.Empty{}, nil
}

// Stop is generated from the source proto contract.
// Classification: special.
func (s *TaskGroupService) Stop(ctx context.Context, req *v11.StopTaskGroupRequest) (*emptypb.Empty, error) {
	_ = ctx
	_ = req

	// TODO: implement TaskGroupService.Stop business logic manually or move it to a manual extension.
	return &emptypb.Empty{}, nil
}

// RunOnce is generated from the source proto contract.
// Classification: special.
func (s *TaskGroupService) RunOnce(ctx context.Context, req *v11.RunTaskGroupOnceRequest) (*emptypb.Empty, error) {
	_ = ctx
	_ = req

	// TODO: implement TaskGroupService.RunOnce business logic manually or move it to a manual extension.
	return &emptypb.Empty{}, nil
}
