// Code generated by xkit.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 18:29:59 CST

package service

// TODO: add TaskGroupService-specific hooks, helpers, and hand-written business logic here.
// Add TaskGroupService-specific hooks and helpers here.
// Tree resources and aggregate child resources should prefer being implemented here first,
// then moved into generated config-backed methods once the contract stabilizes.
// This file is created once and is never overwritten by xkit.
