// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 18:29:59 CST

package service

import (
	adminv1 "admin/api/gen/admin/v1"
	v11 "admin/api/gen/task/v1"
	"admin/internal/data/repo"
	context "context"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"github.com/chnxq/xkitmod/log"
	"github.com/chnxq/xkitpkg/app"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type TaskLogService struct {
	adminv1.TaskLogServiceHTTPServer
	adminv1.UnimplementedTaskLogServiceServer

	log *log.Helper

	taskLogRepo repo.TaskLogRepo
}

func NewTaskLogService(ctx *app.AppCtx, taskLogRepo repo.TaskLogRepo) *TaskLogService {
	return &TaskLogService{
		log:         ctx.NewLoggerHelper("task_log/service"),
		taskLogRepo: taskLogRepo,
	}
}

// List is generated from the source proto contract.
// Classification: standard.
func (s *TaskLogService) List(ctx context.Context, req *v1.PagingRequest) (*v11.ListTaskLogResponse, error) {
	return s.taskLogRepo.List(ctx, req)
}

// Get is generated from the source proto contract.
// Classification: standard.
func (s *TaskLogService) Get(ctx context.Context, req *v11.GetTaskLogRequest) (*v11.TaskLog, error) {
	return s.taskLogRepo.Get(ctx, req)
}

// Delete is generated from the source proto contract.
// Classification: standard.
func (s *TaskLogService) Delete(ctx context.Context, req *v11.DeleteTaskLogRequest) (*emptypb.Empty, error) {
	return s.taskLogRepo.Delete(ctx, req)
}
