// Code generated by: codex.
// generated at        2026-05-10 01:15:00 +08:00.

package repo

import (
	"context"
	"sort"
	"strconv"
	"strings"
	"time"

	auditv1 "admin/api/gen/audit/v1"
	"admin/internal/data/ent"
	"admin/internal/data/ent/apiauditlog"
)

// Add ApiAuditLogRepo-specific query helpers and hand-written data access code here.
// This file is created once and is never overwritten by xkit.

type ApiAuditLogWriter interface {
	WriteApiAuditLog(ctx context.Context, data *auditv1.ApiAuditLog) error
}

type ApiAuditTrendPoint struct {
	Label    string
	Accesses uint64
	Actives  uint64
}

type ApiAuditVisitPoint struct {
	Label string
	Value uint64
}

type ApiAuditNamedValue struct {
	Name  string
	Value uint64
}

type ApiAuditAnalyticsSummary struct {
	TotalAccesses    uint64
	CurrentAccesses  uint64
	TotalDownloads   uint64
	CurrentDownloads uint64
	TotalUsages      uint64
	CurrentActives   uint64
	Trends           []ApiAuditTrendPoint
	Visits           []ApiAuditVisitPoint
	Sources          []ApiAuditNamedValue
	Businesses       []ApiAuditNamedValue
	Platforms        []ApiAuditNamedValue
}

func (r *apiAuditLogRepo) WriteApiAuditLog(ctx context.Context, data *auditv1.ApiAuditLog) error {
	if data == nil {
		return nil
	}

	createdAt := time.Now()
	if data.GetCreatedAt() != nil {
		createdAt = data.GetCreatedAt().AsTime()
	}

	builder := r.entClient.Client().ApiAuditLog.Create().
		SetCreatedAt(createdAt).
		SetNillableTenantID(data.TenantId).
		SetNillableUserID(data.UserId).
		SetNillableUsername(data.Username).
		SetNillableIPAddress(data.IpAddress).
		SetNillableReferer(data.Referer).
		SetNillableAppVersion(data.AppVersion).
		SetNillableHTTPMethod(data.HttpMethod).
		SetNillablePath(data.Path).
		SetNillableRequestURI(data.RequestUri).
		SetNillableAPIModule(data.ApiModule).
		SetNillableAPIOperation(data.ApiOperation).
		SetNillableAPIDescription(data.ApiDescription).
		SetNillableRequestID(data.RequestId).
		SetNillableTraceID(data.TraceId).
		SetNillableSpanID(data.SpanId).
		SetNillableLatencyMs(data.LatencyMs).
		SetNillableSuccess(data.Success).
		SetNillableStatusCode(data.StatusCode).
		SetNillableReason(data.Reason).
		SetNillableRequestHeader(data.RequestHeader).
		SetNillableRequestBody(data.RequestBody).
		SetNillableResponse(data.Response).
		SetNillableLogHash(data.LogHash)

	if data.GeoLocation != nil {
		builder.SetGeoLocation(data.GeoLocation)
	}
	if data.DeviceInfo != nil {
		builder.SetDeviceInfo(data.DeviceInfo)
	}
	if len(data.Signature) > 0 {
		builder.SetSignature(data.Signature)
	}

	if _, err := builder.Save(ctx); err != nil {
		r.log.Errorf("write api audit log failed: %s", err.Error())
		return err
	}
	return nil
}

func (r *apiAuditLogRepo) AnalyticsSummary(ctx context.Context, now time.Time) (*ApiAuditAnalyticsSummary, error) {
	if r == nil || r.entClient == nil {
		return &ApiAuditAnalyticsSummary{}, nil
	}

	since24h := now.Add(-24 * time.Hour)
	since20h := now.Add(-19 * time.Hour).Truncate(time.Hour)
	yearStart := time.Date(now.Year(), time.January, 1, 0, 0, 0, 0, now.Location())

	baseQuery := r.entClient.Client().ApiAuditLog.Query()
	totalAccesses, err := baseQuery.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}
	currentAccesses, err := baseQuery.Clone().Where(apiauditlog.CreatedAtGTE(since24h)).Count(ctx)
	if err != nil {
		return nil, err
	}

	downloadQuery := baseQuery.Clone().Where(
		apiauditlog.Or(
			apiauditlog.PathContainsFold("download"),
			apiauditlog.PathContainsFold("export"),
			apiauditlog.APIOperationContainsFold("download"),
			apiauditlog.APIOperationContainsFold("export"),
		),
	)
	totalDownloads, err := downloadQuery.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}
	currentDownloads, err := downloadQuery.Clone().Where(apiauditlog.CreatedAtGTE(since24h)).Count(ctx)
	if err != nil {
		return nil, err
	}

	totalUsages, err := r.countDistinctUsersAll(ctx)
	if err != nil {
		return nil, err
	}
	currentActives, err := r.countDistinctUsers(ctx, since24h, now)
	if err != nil {
		return nil, err
	}

	yearLogs, err := r.entClient.Client().ApiAuditLog.Query().
		Where(
			apiauditlog.CreatedAtGTE(yearStart),
			apiauditlog.CreatedAtLTE(now),
		).
		All(ctx)
	if err != nil {
		return nil, err
	}

	trends, err := r.buildTrends(ctx, since20h, now)
	if err != nil {
		return nil, err
	}
	visits := buildMonthlyVisits(yearLogs)
	sources := buildTopSourceDistributions(yearLogs, 6)
	businesses := buildTopBusinessDistributions(yearLogs, 6)
	platforms := buildTopPlatformDistributions(yearLogs, 6)

	return &ApiAuditAnalyticsSummary{
		TotalAccesses:    uint64(totalAccesses),
		CurrentAccesses:  uint64(currentAccesses),
		TotalDownloads:   uint64(totalDownloads),
		CurrentDownloads: uint64(currentDownloads),
		TotalUsages:      totalUsages,
		CurrentActives:   currentActives,
		Trends:           trends,
		Visits:           visits,
		Sources:          sources,
		Businesses:       businesses,
		Platforms:        platforms,
	}, nil
}

func (r *apiAuditLogRepo) countDistinctUsers(ctx context.Context, start, end time.Time) (uint64, error) {
	rows := make([]struct {
		UserID uint32 `json:"user_id"`
	}, 0)
	err := r.entClient.Client().ApiAuditLog.Query().
		Where(
			apiauditlog.UserIDNotNil(),
			apiauditlog.CreatedAtGTE(start),
			apiauditlog.CreatedAtLT(end),
		).
		GroupBy(apiauditlog.FieldUserID).
		Scan(ctx, &rows)
	if err != nil {
		return 0, err
	}
	return uint64(len(rows)), nil
}

func (r *apiAuditLogRepo) countDistinctUsersAll(ctx context.Context) (uint64, error) {
	rows := make([]struct {
		UserID uint32 `json:"user_id"`
	}, 0)
	err := r.entClient.Client().ApiAuditLog.Query().
		Where(apiauditlog.UserIDNotNil()).
		GroupBy(apiauditlog.FieldUserID).
		Scan(ctx, &rows)
	if err != nil {
		return 0, err
	}
	return uint64(len(rows)), nil
}

func (r *apiAuditLogRepo) buildTrends(ctx context.Context, start, end time.Time) ([]ApiAuditTrendPoint, error) {
	points := make([]ApiAuditTrendPoint, 0, 20)
	for i := 0; i < 20; i++ {
		hourStart := start.Add(time.Duration(i) * time.Hour)
		hourEnd := hourStart.Add(time.Hour)
		if hourEnd.After(end) {
			hourEnd = end
		}
		if !hourEnd.After(hourStart) {
			hourEnd = hourStart.Add(time.Hour)
		}

		accesses, err := r.entClient.Client().ApiAuditLog.Query().
			Where(
				apiauditlog.CreatedAtGTE(hourStart),
				apiauditlog.CreatedAtLT(hourEnd),
			).
			Count(ctx)
		if err != nil {
			return nil, err
		}

		actives, err := r.countDistinctUsers(ctx, hourStart, hourEnd)
		if err != nil {
			return nil, err
		}

		points = append(points, ApiAuditTrendPoint{
			Label:    hourStart.Format("15:04"),
			Accesses: uint64(accesses),
			Actives:  actives,
		})
	}
	return points, nil
}

func buildMonthlyVisits(items []*ent.ApiAuditLog) []ApiAuditVisitPoint {
	monthMap := make(map[int]uint64, 12)
	for _, item := range items {
		if item == nil || item.CreatedAt == nil {
			continue
		}
		monthMap[int(item.CreatedAt.Month())]++
	}
	visits := make([]ApiAuditVisitPoint, 0, 12)
	for month := 1; month <= 12; month++ {
		visits = append(visits, ApiAuditVisitPoint{
			Label: strconv.Itoa(month),
			Value: monthMap[month],
		})
	}
	return visits
}

func buildTopSourceDistributions(items []*ent.ApiAuditLog, limit int) []ApiAuditNamedValue {
	mapped := make([]ApiAuditNamedValue, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		raw := ""
		if item.Referer != nil {
			raw = *item.Referer
		}
		name := normalizeSourceName(raw)
		mapped = append(mapped, ApiAuditNamedValue{Name: name, Value: 1})
	}
	return topNamedValuesByValue(mapped, limit)
}

func buildTopBusinessDistributions(items []*ent.ApiAuditLog, limit int) []ApiAuditNamedValue {
	mapped := make([]ApiAuditNamedValue, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		name := "unknown"
		if item.APIModule != nil && strings.TrimSpace(*item.APIModule) != "" {
			name = strings.TrimSpace(*item.APIModule)
		}
		mapped = append(mapped, ApiAuditNamedValue{Name: name, Value: 1})
	}
	return topNamedValuesByValue(mapped, limit)
}

func buildTopPlatformDistributions(items []*ent.ApiAuditLog, limit int) []ApiAuditNamedValue {
	mapped := make([]ApiAuditNamedValue, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		platform := normalizePlatformName(item.DeviceInfo)
		mapped = append(mapped, ApiAuditNamedValue{Name: platform, Value: 1})
	}
	return topNamedValuesByValue(mapped, limit)
}

func normalizeSourceName(raw string) string {
	value := strings.TrimSpace(strings.ToLower(raw))
	switch {
	case value == "":
		return "direct"
	case strings.Contains(value, "baidu"), strings.Contains(value, "google"), strings.Contains(value, "bing"), strings.Contains(value, "sogou"), strings.Contains(value, "duckduckgo"):
		return "search"
	case strings.Contains(value, "mail"), strings.Contains(value, "qq.com"), strings.Contains(value, "163.com"), strings.Contains(value, "outlook"), strings.Contains(value, "gmail"):
		return "email"
	case strings.Contains(value, "ad"), strings.Contains(value, "utm_"), strings.Contains(value, "campaign"), strings.Contains(value, "affiliate"):
		return "affiliate"
	default:
		return "other"
	}
}

func normalizePlatformName(deviceInfo *auditv1.DeviceInfo) string {
	if deviceInfo == nil {
		return "other"
	}
	value := strings.TrimSpace(strings.ToLower(deviceInfo.GetPlatform()))
	switch {
	case strings.Contains(value, "android"), strings.Contains(value, "ios"), strings.Contains(value, "mobile"):
		return "mobile"
	case strings.Contains(value, "ipad"), strings.Contains(value, "tablet"):
		return "tablet"
	case strings.Contains(value, "windows"), strings.Contains(value, "mac"), strings.Contains(value, "linux"), strings.Contains(value, "web"):
		return "web"
	case strings.Contains(value, "app"), strings.Contains(value, "client"):
		return "client"
	default:
		return "other"
	}
}

func topNamedValuesByValue(values []ApiAuditNamedValue, limit int) []ApiAuditNamedValue {
	if len(values) == 0 {
		return nil
	}
	collapsed := make(map[string]uint64, len(values))
	for _, item := range values {
		name := strings.TrimSpace(item.Name)
		if name == "" {
			continue
		}
		collapsed[name] += item.Value
	}
	out := make([]ApiAuditNamedValue, 0, len(collapsed))
	for name, value := range collapsed {
		out = append(out, ApiAuditNamedValue{Name: name, Value: value})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Value == out[j].Value {
			return out[i].Name < out[j].Name
		}
		return out[i].Value > out[j].Value
	})
	if limit <= 0 || len(out) <= limit {
		return out
	}
	return out[:limit]
}
