// Code generated by: codex.
// generated at        2026-05-09 23:00:00 +08:00.

package repo

import (
	"context"
	"fmt"
	"time"

	auditv1 "admin/api/gen/audit/v1"
	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"
	"google.golang.org/protobuf/proto"
)

type apiAuditLogAnalyticsReader interface {
	AnalyticsSummary(context.Context, time.Time) (*ApiAuditAnalyticsSummary, error)
}

type wrappedApiAuditLogRepo struct {
	ApiAuditLogRepo
}

func WrapApiAuditLogRepo(base ApiAuditLogRepo) ApiAuditLogRepo {
	if base == nil {
		return nil
	}
	if _, ok := base.(*wrappedApiAuditLogRepo); ok {
		return base
	}
	return &wrappedApiAuditLogRepo{ApiAuditLogRepo: base}
}

func (w *wrappedApiAuditLogRepo) List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListApiAuditLogResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	clonedReq := proto.Clone(req).(*v1.PagingRequest)
	if err := applyApiAuditCreatedAtFilters(clonedReq); err != nil {
		return nil, err
	}
	return w.ApiAuditLogRepo.List(ctx, clonedReq)
}

func (w *wrappedApiAuditLogRepo) WriteApiAuditLog(ctx context.Context, data *auditv1.ApiAuditLog) error {
	if writer, ok := w.ApiAuditLogRepo.(ApiAuditLogWriter); ok {
		return writer.WriteApiAuditLog(ctx, data)
	}
	return nil
}

func (w *wrappedApiAuditLogRepo) AnalyticsSummary(ctx context.Context, now time.Time) (*ApiAuditAnalyticsSummary, error) {
	if reader, ok := w.ApiAuditLogRepo.(apiAuditLogAnalyticsReader); ok {
		return reader.AnalyticsSummary(ctx, now)
	}
	return &ApiAuditAnalyticsSummary{}, nil
}

func (w *wrappedApiAuditLogRepo) CleanupApiAuditLogsBefore(ctx context.Context, tenantID *uint32, before time.Time) (int, error) {
	if cleaner, ok := w.ApiAuditLogRepo.(ApiAuditLogCleaner); ok {
		return cleaner.CleanupApiAuditLogsBefore(ctx, tenantID, before)
	}
	return 0, nil
}

type wrappedLoginAuditLogRepo struct {
	LoginAuditLogRepo
}

func WrapLoginAuditLogRepo(base LoginAuditLogRepo) LoginAuditLogRepo {
	if base == nil {
		return nil
	}
	if _, ok := base.(*wrappedLoginAuditLogRepo); ok {
		return base
	}
	return &wrappedLoginAuditLogRepo{LoginAuditLogRepo: base}
}

func (w *wrappedLoginAuditLogRepo) List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListLoginAuditLogResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	clonedReq := proto.Clone(req).(*v1.PagingRequest)
	if err := applyLoginAuditCreatedAtFilters(clonedReq); err != nil {
		return nil, err
	}
	return w.LoginAuditLogRepo.List(ctx, clonedReq)
}

func (w *wrappedLoginAuditLogRepo) WriteLoginAuditLog(ctx context.Context, data *auditv1.LoginAuditLog) error {
	if writer, ok := w.LoginAuditLogRepo.(LoginAuditLogWriter); ok {
		return writer.WriteLoginAuditLog(ctx, data)
	}
	return nil
}

func (w *wrappedLoginAuditLogRepo) CleanupLoginAuditLogsBefore(ctx context.Context, tenantID *uint32, before time.Time) (int, error) {
	if cleaner, ok := w.LoginAuditLogRepo.(LoginAuditLogCleaner); ok {
		return cleaner.CleanupLoginAuditLogsBefore(ctx, tenantID, before)
	}
	return 0, nil
}

type wrappedPermissionAuditLogRepo struct {
	PermissionAuditLogRepo
}

func WrapPermissionAuditLogRepo(base PermissionAuditLogRepo) PermissionAuditLogRepo {
	if base == nil {
		return nil
	}
	if _, ok := base.(*wrappedPermissionAuditLogRepo); ok {
		return base
	}
	return &wrappedPermissionAuditLogRepo{PermissionAuditLogRepo: base}
}

func (w *wrappedPermissionAuditLogRepo) List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListPermissionAuditLogResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	clonedReq := proto.Clone(req).(*v1.PagingRequest)
	if err := applyPermissionAuditCreatedAtFilters(clonedReq); err != nil {
		return nil, err
	}
	return w.PermissionAuditLogRepo.List(ctx, clonedReq)
}

func (w *wrappedPermissionAuditLogRepo) WritePermissionAuditLog(ctx context.Context, data *auditv1.PermissionAuditLog) error {
	if writer, ok := w.PermissionAuditLogRepo.(PermissionAuditLogWriter); ok {
		return writer.WritePermissionAuditLog(ctx, data)
	}
	return nil
}

func (w *wrappedPermissionAuditLogRepo) CleanupPermissionAuditLogsBefore(ctx context.Context, tenantID *uint32, before time.Time) (int, error) {
	if cleaner, ok := w.PermissionAuditLogRepo.(PermissionAuditLogCleaner); ok {
		return cleaner.CleanupPermissionAuditLogsBefore(ctx, tenantID, before)
	}
	return 0, nil
}
