// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-06 20:20:05 CST

package repo

import (
	dictv1 "admin/api/gen/dict/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/dictcategory"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"strings"

	"time"
)

type DictCategoryRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*dictv1.ListDictCategoryResponse, error)

	Get(ctx context.Context, req *dictv1.GetDictCategoryRequest) (*dictv1.DictCategory, error)

	Create(ctx context.Context, req *dictv1.CreateDictCategoryRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *dictv1.UpdateDictCategoryRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *dictv1.DeleteDictCategoryRequest) (*emptypb.Empty, error)
}

type dictCategoryRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[dictv1.DictCategory, ent.DictCategory]

	repository *entCrud.Repository[
		ent.DictCategoryQuery, ent.DictCategorySelect,
		ent.DictCategoryCreate, ent.DictCategoryCreateBulk,
		ent.DictCategoryUpdate, ent.DictCategoryUpdateOne,
		ent.DictCategoryDelete,
		predicate.DictCategory,
		dictv1.DictCategory, ent.DictCategory,
	]
}

func NewDictCategoryRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *dictCategoryRepo {
	repo := &dictCategoryRepo{
		log:       ctx.NewLoggerHelper("dict_category/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[dictv1.DictCategory, ent.DictCategory](),
	}

	repo.init()

	return repo
}

func (r *dictCategoryRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.DictCategoryQuery, ent.DictCategorySelect,
		ent.DictCategoryCreate, ent.DictCategoryCreateBulk,
		ent.DictCategoryUpdate, ent.DictCategoryUpdateOne,
		ent.DictCategoryDelete,
		predicate.DictCategory,
		dictv1.DictCategory, ent.DictCategory,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func dictCategoryEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func dictCategoryFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func dictCategoryParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *dictCategoryRepo) applyGeneratedFilters(builder *ent.DictCategoryQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(dictcategory.IDEQ(uint32(value)))
			}

		case "parent_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid parent_id filter value: %w", err)
				}
				builder.Where(dictcategory.ParentIDEQ(uint32(value)))
			}

		case "path":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictcategory.PathEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictcategory.PathContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictcategory.PathHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictcategory.PathHasSuffix(condition.GetValue()))
			}

		case "category_key":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictcategory.CategoryKeyEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictcategory.CategoryKeyContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictcategory.CategoryKeyHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictcategory.CategoryKeyHasSuffix(condition.GetValue()))
			}

		case "category_name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictcategory.CategoryNameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictcategory.CategoryNameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictcategory.CategoryNameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictcategory.CategoryNameHasSuffix(condition.GetValue()))
			}

		case "category_level":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(dictcategory.CategoryLevelEQ(dictcategory.CategoryLevel(condition.GetValue())))
			}

		case "scene":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(dictcategory.SceneEQ(dictcategory.Scene(condition.GetValue())))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(dictcategory.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(dictcategory.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(dictcategory.DeletedByEQ(uint32(value)))
			}

		case "sort_order":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid sort_order filter value: %w", err)
				}
				builder.Where(dictcategory.SortOrderEQ(uint32(value)))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(dictcategory.TenantIDEQ(uint32(value)))
			}

		case "remark":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictcategory.RemarkEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictcategory.RemarkContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictcategory.RemarkHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictcategory.RemarkHasSuffix(condition.GetValue()))
			}

		}
	}

	return nil
}

func (r *dictCategoryRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *dictCategoryRepo) List(ctx context.Context, req *v1.PagingRequest) (*dictv1.ListDictCategoryResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().DictCategory.Query()
	countBuilder := r.entClient.Client().DictCategory.Query()
	if tenantID := viewerTenantID(ctx); tenantID != nil {
		builder.Where(dictcategory.Or(
			dictcategory.TenantIDIsNil(),
			dictcategory.TenantIDEQ(platformTenantID),
			dictcategory.TenantIDEQ(*tenantID),
		))
		countBuilder.Where(dictcategory.Or(
			dictcategory.TenantIDIsNil(),
			dictcategory.TenantIDEQ(platformTenantID),
			dictcategory.TenantIDEQ(*tenantID),
		))
	}

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(listReq.Sorting, "sort_order", paginationv1.Sorting_ASC)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}

	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count dict_category failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list dict_category failed: %s", err.Error())
		return nil, err
	}

	items := make([]*dictv1.DictCategory, 0, len(entities))
	if custom, ok := any(r).(interface {
		dictCategoryEnrichListDTOs(context.Context, []*ent.DictCategory) ([]*dictv1.DictCategory, error)
	}); ok {
		items, err = custom.dictCategoryEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &dictv1.ListDictCategoryResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *dictCategoryRepo) Get(ctx context.Context, req *dictv1.GetDictCategoryRequest) (*dictv1.DictCategory, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().DictCategory.Query()
	switch req.GetQueryBy().(type) {
	case *dictv1.GetDictCategoryRequest_Id:
		builder.Where(dictcategory.IDEQ(req.GetId()))
	case *dictv1.GetDictCategoryRequest_CategoryKey:
		builder.Where(dictcategory.CategoryKeyEQ(req.GetCategoryKey()))
	default:
		return nil, fmt.Errorf("invalid query by type")
	}

	entity, err := builder.Only(ctx)
	if err != nil {
		r.log.Errorf("get dict_category failed: %s", err.Error())
		return nil, err
	}
	if err := ensureHybridTenantAccessible(ctx, entity.TenantID); err != nil {
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		dictCategoryEnrichGetDTO(context.Context, []*ent.DictCategory) ([]*dictv1.DictCategory, error)
	}); ok {
		items, err := custom.dictCategoryEnrichGetDTO(ctx, []*ent.DictCategory{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("dict_category relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *dictCategoryRepo) Create(ctx context.Context, req *dictv1.CreateDictCategoryRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictCategoryCustomCreate(ctx context.Context, req *dictv1.CreateDictCategoryRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictCategoryCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().DictCategory.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetCategoryKey(req.Data.GetCategoryKey())
	builder.SetCategoryName(req.Data.GetCategoryName())
	builder.SetCategoryLevel(dictcategory.CategoryLevel(req.Data.GetCategoryLevel().String()))
	builder.SetScene(dictcategory.Scene(req.Data.GetScene().String()))
	builder.SetIsBuiltin(req.Data.GetIsBuiltin())
	builder.SetNillableSortOrder(req.Data.SortOrder)
	builder.SetNillableTenantID(req.Data.TenantId)
	builder.SetNillableRemark(req.Data.Remark)
	builder.SetNillableParentID(req.Data.ParentId)
	builder.SetNillablePath(req.Data.Path)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert dict_category failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *dictCategoryRepo) Update(ctx context.Context, req *dictv1.UpdateDictCategoryRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictCategoryCustomUpdate(ctx context.Context, req *dictv1.UpdateDictCategoryRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictCategoryCustomUpdate(ctx, req)
	}
	builder := r.entClient.Client().DictCategory.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetCategoryKey(req.Data.GetCategoryKey())
	builder.SetCategoryName(req.Data.GetCategoryName())
	builder.SetCategoryLevel(dictcategory.CategoryLevel(req.Data.GetCategoryLevel().String()))
	builder.SetScene(dictcategory.Scene(req.Data.GetScene().String()))
	builder.SetIsBuiltin(req.Data.GetIsBuiltin())
	if req.Data.SortOrder != nil {
		builder.SetNillableSortOrder(req.Data.SortOrder)
	} else if req.GetUpdateMask() != nil && dictCategoryFieldMaskContains(req.GetUpdateMask().GetPaths(), "sort_order", "sortOrder") {
		builder.ClearSortOrder()
	}
	if req.Data.Remark != nil {
		builder.SetNillableRemark(req.Data.Remark)
	} else if req.GetUpdateMask() != nil && dictCategoryFieldMaskContains(req.GetUpdateMask().GetPaths(), "remark") {
		builder.ClearRemark()
	}
	if req.Data.ParentId != nil {
		builder.SetNillableParentID(req.Data.ParentId)
	} else if req.GetUpdateMask() != nil && dictCategoryFieldMaskContains(req.GetUpdateMask().GetPaths(), "parent_id", "parentId") {
		builder.ClearParentID()
	}
	if req.Data.Path != nil {
		builder.SetNillablePath(req.Data.Path)
	} else if req.GetUpdateMask() != nil && dictCategoryFieldMaskContains(req.GetUpdateMask().GetPaths(), "path") {
		builder.ClearPath()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update dict_category failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *dictCategoryRepo) Delete(ctx context.Context, req *dictv1.DeleteDictCategoryRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictCategoryCustomDelete(ctx context.Context, req *dictv1.DeleteDictCategoryRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictCategoryCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		if err := r.entClient.Client().DictCategory.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_category failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		if _, err := r.entClient.Client().DictCategory.Delete().Where(dictcategory.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_category failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
