// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-05-28 15:53:00 CST

package repo

import (
	dictv1 "admin/api/gen/dict/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/dicttype"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"time"
)

type DictTypeRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*dictv1.ListDictTypeResponse, error)

	Get(ctx context.Context, req *dictv1.GetDictTypeRequest) (*dictv1.DictType, error)

	Create(ctx context.Context, req *dictv1.CreateDictTypeRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *dictv1.UpdateDictTypeRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *dictv1.DeleteDictTypeRequest) (*emptypb.Empty, error)
}

type dictTypeRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[dictv1.DictType, ent.DictType]

	repository *entCrud.Repository[
		ent.DictTypeQuery, ent.DictTypeSelect,
		ent.DictTypeCreate, ent.DictTypeCreateBulk,
		ent.DictTypeUpdate, ent.DictTypeUpdateOne,
		ent.DictTypeDelete,
		predicate.DictType,
		dictv1.DictType, ent.DictType,
	]
}

func NewDictTypeRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *dictTypeRepo {
	repo := &dictTypeRepo{
		log:       ctx.NewLoggerHelper("dict_type/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[dictv1.DictType, ent.DictType](),
	}

	repo.init()

	return repo
}

func (r *dictTypeRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.DictTypeQuery, ent.DictTypeSelect,
		ent.DictTypeCreate, ent.DictTypeCreateBulk,
		ent.DictTypeUpdate, ent.DictTypeUpdateOne,
		ent.DictTypeDelete,
		predicate.DictType,
		dictv1.DictType, ent.DictType,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func dictTypeFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func (r *dictTypeRepo) applyGeneratedFilters(builder *ent.DictTypeQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(dicttype.IDEQ(uint32(value)))
			}

		case "type_code":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dicttype.TypeCodeEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dicttype.TypeCodeContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dicttype.TypeCodeHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dicttype.TypeCodeHasSuffix(condition.GetValue()))
			}

		case "type_name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dicttype.TypeNameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dicttype.TypeNameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dicttype.TypeNameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dicttype.TypeNameHasSuffix(condition.GetValue()))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(dicttype.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(dicttype.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(dicttype.DeletedByEQ(uint32(value)))
			}

		case "sort_order":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid sort_order filter value: %w", err)
				}
				builder.Where(dicttype.SortOrderEQ(uint32(value)))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(dicttype.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *dictTypeRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *dictTypeRepo) List(ctx context.Context, req *v1.PagingRequest) (*dictv1.ListDictTypeResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().DictType.Query()
	countBuilder := r.entClient.Client().DictType.Query()
	if tenantID := viewerTenantID(ctx); tenantID != nil {
		builder.Where(dicttype.Or(dicttype.TenantIDIsNil(), dicttype.TenantIDEQ(0), dicttype.TenantIDEQ(*tenantID)))
		countBuilder.Where(dicttype.Or(dicttype.TenantIDIsNil(), dicttype.TenantIDEQ(0), dicttype.TenantIDEQ(*tenantID)))
	}

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"sort_order",
		paginationv1.Sorting_ASC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count dict_type failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list dict_type failed: %s", err.Error())
		return nil, err
	}

	items := make([]*dictv1.DictType, 0, len(entities))
	if custom, ok := any(r).(interface {
		dictTypeEnrichListDTOs(context.Context, []*ent.DictType) ([]*dictv1.DictType, error)
	}); ok {
		items, err = custom.dictTypeEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &dictv1.ListDictTypeResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *dictTypeRepo) Get(ctx context.Context, req *dictv1.GetDictTypeRequest) (*dictv1.DictType, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().DictType.Query()
	entity, err := builder.Where(dicttype.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get dict_type failed: %s", err.Error())
		return nil, err
	}
	if err := ensureHybridTenantAccessible(ctx, entity.TenantID); err != nil {
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		dictTypeEnrichGetDTO(context.Context, []*ent.DictType) ([]*dictv1.DictType, error)
	}); ok {
		items, err := custom.dictTypeEnrichGetDTO(ctx, []*ent.DictType{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("dict_type relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *dictTypeRepo) Create(ctx context.Context, req *dictv1.CreateDictTypeRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictTypeCustomCreate(ctx context.Context, req *dictv1.CreateDictTypeRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictTypeCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().DictType.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetNillableTypeCode(req.Data.TypeCode)
	builder.SetNillableTypeName(req.Data.TypeName)
	builder.SetNillableSortOrder(req.Data.SortOrder)
	builder.SetNillableTenantID(req.Data.TenantId)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert dict_type failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *dictTypeRepo) Update(ctx context.Context, req *dictv1.UpdateDictTypeRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictTypeCustomUpdate(ctx context.Context, req *dictv1.UpdateDictTypeRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictTypeCustomUpdate(ctx, req)
	}

	builder := r.entClient.Client().DictType.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	if req.Data.TypeName != nil {
		builder.SetNillableTypeName(req.Data.TypeName)
	} else if req.GetUpdateMask() != nil && dictTypeFieldMaskContains(req.GetUpdateMask().GetPaths(), "type_name", "typeName") {
		builder.ClearTypeName()
	}
	if req.Data.SortOrder != nil {
		builder.SetNillableSortOrder(req.Data.SortOrder)
	} else if req.GetUpdateMask() != nil && dictTypeFieldMaskContains(req.GetUpdateMask().GetPaths(), "sort_order", "sortOrder") {
		builder.ClearSortOrder()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update dict_type failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *dictTypeRepo) Delete(ctx context.Context, req *dictv1.DeleteDictTypeRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictTypeCustomDelete(ctx context.Context, req *dictv1.DeleteDictTypeRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictTypeCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		if err := r.entClient.Client().DictType.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_type failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		if _, err := r.entClient.Client().DictType.Delete().Where(dicttype.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_type failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
