// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.3.0 2026-06-18
// generated at: 2026-06-26 18:31:12 CST

package repo

import (
	dictv1 "admin/api/gen/dict/v1"

	ent "admin/internal/data/ent"

	"admin/internal/data/ent/dictlabeli18n"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"strings"

	"time"
)

type DictLabelI18nRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*dictv1.ListDictLabelI18NResponse, error)

	Get(ctx context.Context, req *dictv1.GetDictLabelI18NRequest) (*dictv1.DictLabelI18N, error)

	Create(ctx context.Context, req *dictv1.CreateDictLabelI18NRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *dictv1.UpdateDictLabelI18NRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *dictv1.DeleteDictLabelI18NRequest) (*emptypb.Empty, error)
}

type dictLabelI18nRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[dictv1.DictLabelI18N, ent.DictLabelI18n]

	repository *entCrud.Repository[
		ent.DictLabelI18nQuery, ent.DictLabelI18nSelect,
		ent.DictLabelI18nCreate, ent.DictLabelI18nCreateBulk,
		ent.DictLabelI18nUpdate, ent.DictLabelI18nUpdateOne,
		ent.DictLabelI18nDelete,
		predicate.DictLabelI18n,
		dictv1.DictLabelI18N, ent.DictLabelI18n,
	]
}

func NewDictLabelI18nRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *dictLabelI18nRepo {
	repo := &dictLabelI18nRepo{
		log:       ctx.NewLoggerHelper("dict_label_i18n/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[dictv1.DictLabelI18N, ent.DictLabelI18n](),
	}

	repo.init()

	return repo
}

func (r *dictLabelI18nRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.DictLabelI18nQuery, ent.DictLabelI18nSelect,
		ent.DictLabelI18nCreate, ent.DictLabelI18nCreateBulk,
		ent.DictLabelI18nUpdate, ent.DictLabelI18nUpdateOne,
		ent.DictLabelI18nDelete,
		predicate.DictLabelI18n,
		dictv1.DictLabelI18N, ent.DictLabelI18n,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func dictLabelI18nFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func dictLabelI18nParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *dictLabelI18nRepo) applyGeneratedFilters(builder *ent.DictLabelI18nQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(dictlabeli18n.IDEQ(uint32(value)))
			}

		case "label_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid label_id filter value: %w", err)
				}
				builder.Where(dictlabeli18n.LabelIDEQ(uint32(value)))
			}

		case "language_code":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictlabeli18n.LanguageCodeEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictlabeli18n.LanguageCodeContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictlabeli18n.LanguageCodeHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictlabeli18n.LanguageCodeHasSuffix(condition.GetValue()))
			}

		case "text_value":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictlabeli18n.TextValueEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictlabeli18n.TextValueContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictlabeli18n.TextValueHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictlabeli18n.TextValueHasSuffix(condition.GetValue()))
			}

		case "short_text":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(dictlabeli18n.ShortTextEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(dictlabeli18n.ShortTextContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(dictlabeli18n.ShortTextHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(dictlabeli18n.ShortTextHasSuffix(condition.GetValue()))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(dictlabeli18n.TenantIDEQ(uint32(value)))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(dictlabeli18n.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(dictlabeli18n.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(dictlabeli18n.DeletedByEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *dictLabelI18nRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *dictLabelI18nRepo) List(ctx context.Context, req *v1.PagingRequest) (*dictv1.ListDictLabelI18NResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	pagingReq := req
	var err error

	builder := r.entClient.Client().DictLabelI18n.Query()
	countBuilder := r.entClient.Client().DictLabelI18n.Query()
	if custom, ok := any(r).(interface {
		dictLabelI18nRepoCustomList(context.Context, *ent.DictLabelI18nQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.dictLabelI18nRepoCustomList(ctx, builder, pagingReq)
		if err != nil {
			return nil, err
		}
	}
	if custom, ok := any(r).(interface {
		dictLabelI18nRepoCustomList(context.Context, *ent.DictLabelI18nQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.dictLabelI18nRepoCustomList(ctx, countBuilder, pagingReq)
		if err != nil {
			return nil, err
		}
	}

	if err := r.applyGeneratedFilters(builder, pagingReq); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, pagingReq); err != nil {
		return nil, err
	}

	listReq := pagingReq
	if listReq == nil {
		listReq = &paginationv1.PagingRequest{}
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"id",
		paginationv1.Sorting_ASC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := listReq.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	sortField, sortDirection, err := firstSorting(listReq)
	if err != nil {
		return nil, err
	}
	if sortField != "" {
		switch sortDirection {
		case paginationv1.Sorting_DESC:
			builder.Order(ent.Desc(sortField))
		default:
			builder.Order(ent.Asc(sortField))
		}
	}
	offset, limit, applyPaging, err := resolvePaging(listReq)
	if err != nil {
		return nil, err
	}
	if applyPaging {
		builder.Offset(offset)
		builder.Limit(limit)
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count dict_label_i18n failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list dict_label_i18n failed: %s", err.Error())
		return nil, err
	}

	items := make([]*dictv1.DictLabelI18N, 0, len(entities))
	if custom, ok := any(r).(interface {
		dictLabelI18nEnrichListDTOs(context.Context, []*ent.DictLabelI18n) ([]*dictv1.DictLabelI18N, error)
	}); ok {
		items, err = custom.dictLabelI18nEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &dictv1.ListDictLabelI18NResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *dictLabelI18nRepo) Get(ctx context.Context, req *dictv1.GetDictLabelI18NRequest) (*dictv1.DictLabelI18N, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().DictLabelI18n.Query()
	entity, err := builder.Where(dictlabeli18n.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get dict_label_i18n failed: %s", err.Error())
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		dictLabelI18nEnrichGetDTO(context.Context, []*ent.DictLabelI18n) ([]*dictv1.DictLabelI18N, error)
	}); ok {
		items, err := custom.dictLabelI18nEnrichGetDTO(ctx, []*ent.DictLabelI18n{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("dict_label_i18n relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *dictLabelI18nRepo) Create(ctx context.Context, req *dictv1.CreateDictLabelI18NRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictLabelI18nCustomCreate(ctx context.Context, req *dictv1.CreateDictLabelI18NRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictLabelI18nCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().DictLabelI18n.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetLabelID(req.Data.GetLabelId())
	builder.SetLanguageCode(req.Data.GetLanguageCode())
	builder.SetTextValue(req.Data.GetTextValue())
	builder.SetNillableShortText(req.Data.ShortText)
	builder.SetNillableTenantID(req.Data.TenantId)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert dict_label_i18n failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *dictLabelI18nRepo) Update(ctx context.Context, req *dictv1.UpdateDictLabelI18NRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictLabelI18nCustomUpdate(ctx context.Context, req *dictv1.UpdateDictLabelI18NRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictLabelI18nCustomUpdate(ctx, req)
	}
	builder := r.entClient.Client().DictLabelI18n.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetLabelID(req.Data.GetLabelId())
	builder.SetTextValue(req.Data.GetTextValue())
	if req.Data.ShortText != nil {
		builder.SetNillableShortText(req.Data.ShortText)
	} else if req.GetUpdateMask() != nil && dictLabelI18nFieldMaskContains(req.GetUpdateMask().GetPaths(), "short_text", "shortText") {
		builder.ClearShortText()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update dict_label_i18n failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *dictLabelI18nRepo) Delete(ctx context.Context, req *dictv1.DeleteDictLabelI18NRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		dictLabelI18nCustomDelete(ctx context.Context, req *dictv1.DeleteDictLabelI18NRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.dictLabelI18nCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		if err := r.entClient.Client().DictLabelI18n.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_label_i18n failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		if _, err := r.entClient.Client().DictLabelI18n.Delete().Where(dictlabeli18n.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_label_i18n failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
