// Code generated by xkit.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 22:51:11 CST

package repo

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	dictv1 "admin/api/gen/dict/v1"
	identityv1 "admin/api/gen/identity/v1"
	"admin/internal/data/ent"
	"admin/internal/data/ent/dictcategory"
	"admin/internal/data/ent/dictlabel"
	"admin/internal/data/ent/dictlabeli18n"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Add DictLabelRepo-specific query helpers and hand-written data access code here.
// Tree assembly, aggregate hydration, and child-table orchestration belong here when they
// are not yet safe to fully generate from config.
// This file is created once and is never overwritten by xkit.

func (r *dictLabelRepo) attachDictLabelDetails(ctx context.Context, entities []*ent.DictLabel) ([]*dictv1.DictLabel, error) {
	items := make([]*dictv1.DictLabel, 0, len(entities))
	tenantIDs := make([]uint32, 0, len(entities))
	labelIDs := make([]uint32, 0, len(entities))
	categoryIDs := make([]uint32, 0, len(entities))
	for _, entity := range entities {
		if entity == nil {
			continue
		}
		tenantIDs = append(tenantIDs, collectTenantIDs(entity.TenantID)...)
		labelIDs = append(labelIDs, entity.ID)
		categoryIDs = append(categoryIDs, entity.CategoryID)
	}
	tenantNameMap := loadTenantNameMap(ctx, r.entClient.Client(), tenantIDs)
	categoryKeyMap := make(map[uint32]string)
	if len(categoryIDs) > 0 {
		rows, err := r.entClient.Client().DictCategory.Query().Where(dictcategory.IDIn(categoryIDs...)).All(ctx)
		if err != nil {
			return nil, err
		}
		for _, row := range rows {
			if row == nil {
				continue
			}
			categoryKeyMap[row.ID] = row.CategoryKey
		}
	}
	i18nByLabel := make(map[uint32][]*dictv1.DictLabelI18N)
	if len(labelIDs) > 0 {
		rows, err := r.entClient.Client().DictLabelI18n.Query().Where(dictlabeli18n.LabelIDIn(labelIDs...)).All(ctx)
		if err != nil {
			return nil, err
		}
		for _, row := range rows {
			if row == nil {
				continue
			}
			dto := dictLabelI18nRowToDTO(row)
			if dto == nil {
				continue
			}
			i18nByLabel[row.LabelID] = append(i18nByLabel[row.LabelID], dto)
		}
	}

	for _, entity := range entities {
		if entity == nil {
			continue
		}
		dto := r.mapper.ToDTO(entity)
		if dto == nil {
			continue
		}
		dto.TenantName = tenantNameFromMap(tenantNameMap, entity.TenantID)
		if categoryKey, ok := categoryKeyMap[entity.CategoryID]; ok && categoryKey != "" {
			dto.CategoryKey = &categoryKey
		}
		if itemsI18n := i18nByLabel[entity.ID]; len(itemsI18n) > 0 {
			dto.ItemsI18N = itemsI18n
			dto.CurrentI18N = itemsI18n[0]
		}
		items = append(items, dto)
	}
	return items, nil
}

func dictLabelI18nRowToDTO(row *ent.DictLabelI18n) *dictv1.DictLabelI18N {
	if row == nil {
		return nil
	}
	dto := &dictv1.DictLabelI18N{
		Id:           &row.ID,
		LabelId:      &row.LabelID,
		LanguageCode: &row.LanguageCode,
		TextValue:    &row.TextValue,
		TenantId:     row.TenantID,
		CreatedBy:    row.CreatedBy,
		UpdatedBy:    row.UpdatedBy,
		DeletedBy:    row.DeletedBy,
	}
	if row.ShortText != nil {
		dto.ShortText = row.ShortText
	}
	if row.CreatedAt != nil {
		dto.CreatedAt = timestamppb.New(*row.CreatedAt)
	}
	if row.UpdatedAt != nil {
		dto.UpdatedAt = timestamppb.New(*row.UpdatedAt)
	}
	if row.DeletedAt != nil {
		dto.DeletedAt = timestamppb.New(*row.DeletedAt)
	}
	return dto
}

func validateDictLabelCategoryTenant(ctx context.Context, txClient *ent.Client, categoryID uint32, labelTenantID *uint32) (*uint32, error) {
	if categoryID == 0 {
		return nil, fmt.Errorf("invalid dict category id")
	}
	categoryEntity, err := txClient.DictCategory.Query().Where(dictcategory.IDEQ(categoryID)).Only(ctx)
	if err != nil {
		return nil, err
	}
	if err := ensureHybridTenantAccessible(ctx, categoryEntity.TenantID); err != nil {
		return nil, err
	}
	if labelTenantID == nil {
		if categoryEntity.TenantID == nil || *categoryEntity.TenantID == platformTenantID {
			return nil, nil
		}
		return nil, identityv1.ErrorForbidden("cross-tenant access is forbidden")
	}
	if categoryEntity.TenantID == nil {
		return nil, identityv1.ErrorForbidden("cross-tenant access is forbidden")
	}
	if *labelTenantID != *categoryEntity.TenantID {
		return nil, identityv1.ErrorForbidden("cross-tenant access is forbidden")
	}
	return categoryEntity.TenantID, nil
}

func (r *dictLabelRepo) dictLabelEnrichListDTOs(ctx context.Context, entities []*ent.DictLabel) ([]*dictv1.DictLabel, error) {
	return r.attachDictLabelDetails(ctx, entities)
}

func (r *dictLabelRepo) dictLabelEnrichGetDTO(ctx context.Context, entities []*ent.DictLabel) ([]*dictv1.DictLabel, error) {
	return r.attachDictLabelDetails(ctx, entities)
}

func (r *dictLabelRepo) dictLabelCustomCreate(ctx context.Context, req *dictv1.CreateDictLabelRequest) (*emptypb.Empty, error) {
	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().DictLabel.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetCategoryID(req.Data.GetCategoryId())
	builder.SetLabelKey(req.Data.GetLabelKey())
	builder.SetNillableLabelCode(req.Data.LabelCode)
	builder.SetLabelKind(dictlabel.LabelKind(req.Data.GetLabelKind().String()))
	builder.SetNillableDefaultText(req.Data.DefaultText)
	if req.Data.PayloadJson != nil {
		payloadJSON := strings.TrimSpace(req.Data.GetPayloadJson())
		payloadValue := map[string]any{}
		if payloadJSON != "" {
			if err := json.Unmarshal([]byte(payloadJSON), &payloadValue); err != nil {
				return nil, fmt.Errorf("invalid payload_json: %w", err)
			}
		}
		builder.SetPayloadJSON(payloadValue)
	}
	builder.SetIsBuiltin(req.Data.GetIsBuiltin())
	builder.SetStatus(dictlabel.Status(req.Data.GetStatus().String()))
	builder.SetNillableSortOrder(req.Data.SortOrder)
	tenantID, err := resolveCreateTenantID(ctx, req.Data.TenantId)
	if err != nil {
		return nil, err
	}
	resolvedTenantID, err := validateDictLabelCategoryTenant(ctx, r.entClient.Client(), req.Data.GetCategoryId(), tenantID)
	if err != nil {
		return nil, err
	}
	builder.SetNillableTenantID(resolvedTenantID)
	builder.SetNillableRemark(req.Data.Remark)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	if _, err := builder.Save(ctx); err != nil {
		r.log.Errorf("insert dict_label failed: %s", err.Error())
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func (r *dictLabelRepo) dictLabelCustomUpdate(ctx context.Context, req *dictv1.UpdateDictLabelRequest) (*emptypb.Empty, error) {
	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	current, err := r.entClient.Client().DictLabel.Query().Where(dictlabel.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get dict_label before update failed: %s", err.Error())
		return nil, err
	}
	if err := ensureHybridTenantMutable(ctx, current.TenantID); err != nil {
		return nil, err
	}

	categoryID := current.CategoryID
	if req.Data.CategoryId != nil {
		categoryID = req.Data.GetCategoryId()
	}
	if _, err := validateDictLabelCategoryTenant(ctx, r.entClient.Client(), categoryID, current.TenantID); err != nil {
		return nil, err
	}

	builder := r.entClient.Client().DictLabel.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetCategoryID(categoryID)
	if req.Data.LabelCode != nil {
		builder.SetNillableLabelCode(req.Data.LabelCode)
	} else if req.GetUpdateMask() != nil && dictLabelFieldMaskContains(req.GetUpdateMask().GetPaths(), "label_code", "labelCode") {
		builder.ClearLabelCode()
	}
	builder.SetLabelKind(dictlabel.LabelKind(req.Data.GetLabelKind().String()))
	if req.Data.DefaultText != nil {
		builder.SetNillableDefaultText(req.Data.DefaultText)
	} else if req.GetUpdateMask() != nil && dictLabelFieldMaskContains(req.GetUpdateMask().GetPaths(), "default_text", "defaultText") {
		builder.ClearDefaultText()
	}
	if req.Data.PayloadJson != nil {
		payloadJSON := strings.TrimSpace(req.Data.GetPayloadJson())
		payloadValue := map[string]any{}
		if payloadJSON != "" {
			if err := json.Unmarshal([]byte(payloadJSON), &payloadValue); err != nil {
				return nil, fmt.Errorf("invalid payload_json: %w", err)
			}
		}
		builder.SetPayloadJSON(payloadValue)
	} else if req.GetUpdateMask() != nil && dictLabelFieldMaskContains(req.GetUpdateMask().GetPaths(), "payload_json", "payloadJson") {
		builder.ClearPayloadJSON()
	}
	builder.SetIsBuiltin(req.Data.GetIsBuiltin())
	builder.SetStatus(dictlabel.Status(req.Data.GetStatus().String()))
	if req.Data.SortOrder != nil {
		builder.SetNillableSortOrder(req.Data.SortOrder)
	} else if req.GetUpdateMask() != nil && dictLabelFieldMaskContains(req.GetUpdateMask().GetPaths(), "sort_order", "sortOrder") {
		builder.ClearSortOrder()
	}
	if req.Data.Remark != nil {
		builder.SetNillableRemark(req.Data.Remark)
	} else if req.GetUpdateMask() != nil && dictLabelFieldMaskContains(req.GetUpdateMask().GetPaths(), "remark") {
		builder.ClearRemark()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	if err := builder.Exec(ctx); err != nil {
		r.log.Errorf("update dict_label failed: %s", err.Error())
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func (r *dictLabelRepo) dictLabelCustomDelete(ctx context.Context, req *dictv1.DeleteDictLabelRequest) (*emptypb.Empty, error) {
	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		entity, err := r.entClient.Client().DictLabel.Query().Where(dictlabel.IDEQ(typedReq.GetId())).Only(ctx)
		if err != nil {
			r.log.Errorf("load dict_label before delete failed: %s", err.Error())
			return nil, err
		}
		if err := ensureHybridTenantMutable(ctx, entity.TenantID); err != nil {
			return nil, err
		}
		if err := r.entClient.Client().DictLabel.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_label failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		entities, err := r.entClient.Client().DictLabel.Query().Where(dictlabel.IDIn(typedReq.GetIds()...)).All(ctx)
		if err != nil {
			r.log.Errorf("load dict_labels before delete failed: %s", err.Error())
			return nil, err
		}
		for _, entity := range entities {
			if entity == nil {
				continue
			}
			if err := ensureHybridTenantMutable(ctx, entity.TenantID); err != nil {
				return nil, err
			}
		}
		if _, err := r.entClient.Client().DictLabel.Delete().Where(dictlabel.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete dict_label failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return &emptypb.Empty{}, nil
}
