// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-06 20:20:05 CST

package repo

import (
	storagev1 "admin/api/gen/storage/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/file"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"strings"

	"time"
)

type FileRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*storagev1.ListFileResponse, error)

	Get(ctx context.Context, req *storagev1.GetFileRequest) (*storagev1.File, error)

	Create(ctx context.Context, req *storagev1.CreateFileRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *storagev1.UpdateFileRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *storagev1.DeleteFileRequest) (*emptypb.Empty, error)
}

type fileRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[storagev1.File, ent.File]

	repository *entCrud.Repository[
		ent.FileQuery, ent.FileSelect,
		ent.FileCreate, ent.FileCreateBulk,
		ent.FileUpdate, ent.FileUpdateOne,
		ent.FileDelete,
		predicate.File,
		storagev1.File, ent.File,
	]
}

func NewFileRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *fileRepo {
	repo := &fileRepo{
		log:       ctx.NewLoggerHelper("file/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[storagev1.File, ent.File](),
	}

	repo.init()

	return repo
}

func (r *fileRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.FileQuery, ent.FileSelect,
		ent.FileCreate, ent.FileCreateBulk,
		ent.FileUpdate, ent.FileUpdateOne,
		ent.FileDelete,
		predicate.File,
		storagev1.File, ent.File,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func fileEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func fileFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func fileParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *fileRepo) applyGeneratedFilters(builder *ent.FileQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(file.IDEQ(uint32(value)))
			}

		case "provider":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(file.ProviderEQ(file.Provider(condition.GetValue())))
			}

		case "bucket_name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.BucketNameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.BucketNameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.BucketNameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.BucketNameHasSuffix(condition.GetValue()))
			}

		case "file_directory":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.FileDirectoryEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.FileDirectoryContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.FileDirectoryHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.FileDirectoryHasSuffix(condition.GetValue()))
			}

		case "file_guid":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.FileGUIDEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.FileGUIDContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.FileGUIDHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.FileGUIDHasSuffix(condition.GetValue()))
			}

		case "save_file_name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.SaveFileNameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.SaveFileNameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.SaveFileNameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.SaveFileNameHasSuffix(condition.GetValue()))
			}

		case "file_name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.FileNameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.FileNameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.FileNameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.FileNameHasSuffix(condition.GetValue()))
			}

		case "extension":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.ExtensionEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.ExtensionContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.ExtensionHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.ExtensionHasSuffix(condition.GetValue()))
			}

		case "size":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 64)
				if err != nil {
					return fmt.Errorf("invalid size filter value: %w", err)
				}
				builder.Where(file.SizeEQ(uint64(value)))
			}

		case "size_format":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.SizeFormatEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.SizeFormatContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.SizeFormatHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.SizeFormatHasSuffix(condition.GetValue()))
			}

		case "link_url":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.LinkURLEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.LinkURLContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.LinkURLHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.LinkURLHasSuffix(condition.GetValue()))
			}

		case "content_hash":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.ContentHashEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.ContentHashContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.ContentHashHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.ContentHashHasSuffix(condition.GetValue()))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(file.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(file.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(file.DeletedByEQ(uint32(value)))
			}

		case "remark":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(file.RemarkEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(file.RemarkContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(file.RemarkHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(file.RemarkHasSuffix(condition.GetValue()))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(file.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *fileRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *fileRepo) List(ctx context.Context, req *v1.PagingRequest) (*storagev1.ListFileResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().File.Query()
	countBuilder := r.entClient.Client().File.Query()
	if tenantID := viewerTenantID(ctx); tenantID != nil {
		builder.Where(file.TenantIDEQ(*tenantID))
		countBuilder.Where(file.TenantIDEQ(*tenantID))
	}

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"id",
		paginationv1.Sorting_ASC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count file failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list file failed: %s", err.Error())
		return nil, err
	}

	items := make([]*storagev1.File, 0, len(entities))
	if custom, ok := any(r).(interface {
		fileEnrichListDTOs(context.Context, []*ent.File) ([]*storagev1.File, error)
	}); ok {
		items, err = custom.fileEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &storagev1.ListFileResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *fileRepo) Get(ctx context.Context, req *storagev1.GetFileRequest) (*storagev1.File, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().File.Query()
	entity, err := builder.Where(file.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get file failed: %s", err.Error())
		return nil, err
	}
	if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		fileEnrichGetDTO(context.Context, []*ent.File) ([]*storagev1.File, error)
	}); ok {
		items, err := custom.fileEnrichGetDTO(ctx, []*ent.File{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("file relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *fileRepo) Create(ctx context.Context, req *storagev1.CreateFileRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		fileCustomCreate(ctx context.Context, req *storagev1.CreateFileRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.fileCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().File.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetNillableProvider(fileEnumPtrFromProto[file.Provider](req.Data.Provider))
	builder.SetNillableBucketName(req.Data.BucketName)
	builder.SetNillableFileDirectory(req.Data.FileDirectory)
	builder.SetNillableFileGUID(req.Data.FileGuid)
	builder.SetNillableSaveFileName(req.Data.SaveFileName)
	builder.SetNillableFileName(req.Data.FileName)
	builder.SetNillableExtension(req.Data.Extension)
	builder.SetNillableSize(req.Data.Size)
	builder.SetNillableSizeFormat(req.Data.SizeFormat)
	builder.SetNillableLinkURL(req.Data.LinkUrl)
	builder.SetNillableContentHash(req.Data.ContentHash)
	tenantID, err := resolveCreateTenantID(ctx, req.Data.TenantId)
	if err != nil {
		return nil, err
	}
	builder.SetNillableTenantID(tenantID)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert file failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *fileRepo) Update(ctx context.Context, req *storagev1.UpdateFileRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		fileCustomUpdate(ctx context.Context, req *storagev1.UpdateFileRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.fileCustomUpdate(ctx, req)
	}
	current, err := r.entClient.Client().File.Query().Where(file.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get file before update failed: %s", err.Error())
		return nil, err
	}
	if err := ensureTenantAccessible(ctx, current.TenantID); err != nil {
		return nil, err
	}
	builder := r.entClient.Client().File.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	if req.Data.Provider != nil {
		builder.SetNillableProvider(fileEnumPtrFromProto[file.Provider](req.Data.Provider))
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "provider") {
		builder.ClearProvider()
	}
	if req.Data.BucketName != nil {
		builder.SetNillableBucketName(req.Data.BucketName)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "bucket_name", "bucketName") {
		builder.ClearBucketName()
	}
	if req.Data.FileDirectory != nil {
		builder.SetNillableFileDirectory(req.Data.FileDirectory)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "file_directory", "fileDirectory") {
		builder.ClearFileDirectory()
	}
	if req.Data.FileGuid != nil {
		builder.SetNillableFileGUID(req.Data.FileGuid)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "file_guid", "fileGuid") {
		builder.ClearFileGUID()
	}
	if req.Data.SaveFileName != nil {
		builder.SetNillableSaveFileName(req.Data.SaveFileName)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "save_file_name", "saveFileName") {
		builder.ClearSaveFileName()
	}
	if req.Data.FileName != nil {
		builder.SetNillableFileName(req.Data.FileName)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "file_name", "fileName") {
		builder.ClearFileName()
	}
	if req.Data.Extension != nil {
		builder.SetNillableExtension(req.Data.Extension)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "extension") {
		builder.ClearExtension()
	}
	if req.Data.Size != nil {
		builder.SetNillableSize(req.Data.Size)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "size") {
		builder.ClearSize()
	}
	if req.Data.SizeFormat != nil {
		builder.SetNillableSizeFormat(req.Data.SizeFormat)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "size_format", "sizeFormat") {
		builder.ClearSizeFormat()
	}
	if req.Data.LinkUrl != nil {
		builder.SetNillableLinkURL(req.Data.LinkUrl)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "link_url", "linkUrl") {
		builder.ClearLinkURL()
	}
	if req.Data.ContentHash != nil {
		builder.SetNillableContentHash(req.Data.ContentHash)
	} else if req.GetUpdateMask() != nil && fileFieldMaskContains(req.GetUpdateMask().GetPaths(), "content_hash", "contentHash") {
		builder.ClearContentHash()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update file failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *fileRepo) Delete(ctx context.Context, req *storagev1.DeleteFileRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		fileCustomDelete(ctx context.Context, req *storagev1.DeleteFileRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.fileCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		entity, err := r.entClient.Client().File.Query().Where(file.IDEQ(typedReq.GetId())).Only(ctx)
		if err != nil {
			r.log.Errorf("get file before delete failed: %s", err.Error())
			return nil, err
		}
		if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
			return nil, err
		}
		if err := r.entClient.Client().File.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete file failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		entities, err := r.entClient.Client().File.Query().Where(file.IDIn(typedReq.GetIds()...)).All(ctx)
		if err != nil {
			r.log.Errorf("list files before delete failed: %s", err.Error())
			return nil, err
		}
		for _, entity := range entities {
			if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
				return nil, err
			}
		}
		if _, err := r.entClient.Client().File.Delete().Where(file.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete file failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
