// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-06 20:20:05 CST

package repo

import (
	authenticationv1 "admin/api/gen/authentication/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/loginpolicy"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"strings"

	"time"
)

type LoginPolicyRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*authenticationv1.ListLoginPolicyResponse, error)

	Get(ctx context.Context, req *authenticationv1.GetLoginPolicyRequest) (*authenticationv1.LoginPolicy, error)

	Create(ctx context.Context, req *authenticationv1.CreateLoginPolicyRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *authenticationv1.UpdateLoginPolicyRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *authenticationv1.DeleteLoginPolicyRequest) (*emptypb.Empty, error)
}

type loginPolicyRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[authenticationv1.LoginPolicy, ent.LoginPolicy]

	repository *entCrud.Repository[
		ent.LoginPolicyQuery, ent.LoginPolicySelect,
		ent.LoginPolicyCreate, ent.LoginPolicyCreateBulk,
		ent.LoginPolicyUpdate, ent.LoginPolicyUpdateOne,
		ent.LoginPolicyDelete,
		predicate.LoginPolicy,
		authenticationv1.LoginPolicy, ent.LoginPolicy,
	]
}

func NewLoginPolicyRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *loginPolicyRepo {
	repo := &loginPolicyRepo{
		log:       ctx.NewLoggerHelper("login_policy/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[authenticationv1.LoginPolicy, ent.LoginPolicy](),
	}

	repo.init()

	return repo
}

func (r *loginPolicyRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.LoginPolicyQuery, ent.LoginPolicySelect,
		ent.LoginPolicyCreate, ent.LoginPolicyCreateBulk,
		ent.LoginPolicyUpdate, ent.LoginPolicyUpdateOne,
		ent.LoginPolicyDelete,
		predicate.LoginPolicy,
		authenticationv1.LoginPolicy, ent.LoginPolicy,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func loginPolicyEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func loginPolicyFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func loginPolicyParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *loginPolicyRepo) applyGeneratedFilters(builder *ent.LoginPolicyQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(loginpolicy.IDEQ(uint32(value)))
			}

		case "target_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid target_id filter value: %w", err)
				}
				builder.Where(loginpolicy.TargetIDEQ(uint32(value)))
			}

		case "value":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(loginpolicy.ValueEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(loginpolicy.ValueContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(loginpolicy.ValueHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(loginpolicy.ValueHasSuffix(condition.GetValue()))
			}

		case "reason":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(loginpolicy.ReasonEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(loginpolicy.ReasonContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(loginpolicy.ReasonHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(loginpolicy.ReasonHasSuffix(condition.GetValue()))
			}

		case "type":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(loginpolicy.TypeEQ(loginpolicy.Type(condition.GetValue())))
			}

		case "method":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(loginpolicy.MethodEQ(loginpolicy.Method(condition.GetValue())))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(loginpolicy.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(loginpolicy.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(loginpolicy.DeletedByEQ(uint32(value)))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(loginpolicy.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *loginPolicyRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *loginPolicyRepo) List(ctx context.Context, req *v1.PagingRequest) (*authenticationv1.ListLoginPolicyResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().LoginPolicy.Query()
	countBuilder := r.entClient.Client().LoginPolicy.Query()
	if tenantID := viewerTenantID(ctx); tenantID != nil {
		builder.Where(loginpolicy.TenantIDEQ(*tenantID))
		countBuilder.Where(loginpolicy.TenantIDEQ(*tenantID))
	}

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"created_at",
		paginationv1.Sorting_DESC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count login_policy failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list login_policy failed: %s", err.Error())
		return nil, err
	}

	items := make([]*authenticationv1.LoginPolicy, 0, len(entities))
	if custom, ok := any(r).(interface {
		loginPolicyEnrichListDTOs(context.Context, []*ent.LoginPolicy) ([]*authenticationv1.LoginPolicy, error)
	}); ok {
		items, err = custom.loginPolicyEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &authenticationv1.ListLoginPolicyResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *loginPolicyRepo) Get(ctx context.Context, req *authenticationv1.GetLoginPolicyRequest) (*authenticationv1.LoginPolicy, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().LoginPolicy.Query()
	entity, err := builder.Where(loginpolicy.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get login_policy failed: %s", err.Error())
		return nil, err
	}
	if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		loginPolicyEnrichGetDTO(context.Context, []*ent.LoginPolicy) ([]*authenticationv1.LoginPolicy, error)
	}); ok {
		items, err := custom.loginPolicyEnrichGetDTO(ctx, []*ent.LoginPolicy{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("login_policy relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *loginPolicyRepo) Create(ctx context.Context, req *authenticationv1.CreateLoginPolicyRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		loginPolicyCustomCreate(ctx context.Context, req *authenticationv1.CreateLoginPolicyRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.loginPolicyCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().LoginPolicy.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetNillableTargetID(req.Data.TargetId)
	builder.SetNillableValue(req.Data.Value)
	builder.SetNillableReason(req.Data.Reason)
	builder.SetNillableType(loginPolicyEnumPtrFromProto[loginpolicy.Type](req.Data.Type))
	builder.SetNillableMethod(loginPolicyEnumPtrFromProto[loginpolicy.Method](req.Data.Method))
	tenantID, err := resolveCreateTenantID(ctx, req.Data.TenantId)
	if err != nil {
		return nil, err
	}
	builder.SetNillableTenantID(tenantID)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert login_policy failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *loginPolicyRepo) Update(ctx context.Context, req *authenticationv1.UpdateLoginPolicyRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		loginPolicyCustomUpdate(ctx context.Context, req *authenticationv1.UpdateLoginPolicyRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.loginPolicyCustomUpdate(ctx, req)
	}
	current, err := r.entClient.Client().LoginPolicy.Query().Where(loginpolicy.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get login_policy before update failed: %s", err.Error())
		return nil, err
	}
	if err := ensureTenantAccessible(ctx, current.TenantID); err != nil {
		return nil, err
	}
	builder := r.entClient.Client().LoginPolicy.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	if req.Data.TargetId != nil {
		builder.SetNillableTargetID(req.Data.TargetId)
	} else if req.GetUpdateMask() != nil && loginPolicyFieldMaskContains(req.GetUpdateMask().GetPaths(), "target_id", "targetId") {
		builder.ClearTargetID()
	}
	if req.Data.Value != nil {
		builder.SetNillableValue(req.Data.Value)
	} else if req.GetUpdateMask() != nil && loginPolicyFieldMaskContains(req.GetUpdateMask().GetPaths(), "value") {
		builder.ClearValue()
	}
	if req.Data.Reason != nil {
		builder.SetNillableReason(req.Data.Reason)
	} else if req.GetUpdateMask() != nil && loginPolicyFieldMaskContains(req.GetUpdateMask().GetPaths(), "reason") {
		builder.ClearReason()
	}
	if req.Data.Type != nil {
		builder.SetNillableType(loginPolicyEnumPtrFromProto[loginpolicy.Type](req.Data.Type))
	} else if req.GetUpdateMask() != nil && loginPolicyFieldMaskContains(req.GetUpdateMask().GetPaths(), "type") {
		builder.ClearType()
	}
	if req.Data.Method != nil {
		builder.SetNillableMethod(loginPolicyEnumPtrFromProto[loginpolicy.Method](req.Data.Method))
	} else if req.GetUpdateMask() != nil && loginPolicyFieldMaskContains(req.GetUpdateMask().GetPaths(), "method") {
		builder.ClearMethod()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update login_policy failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *loginPolicyRepo) Delete(ctx context.Context, req *authenticationv1.DeleteLoginPolicyRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		loginPolicyCustomDelete(ctx context.Context, req *authenticationv1.DeleteLoginPolicyRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.loginPolicyCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		entity, err := r.entClient.Client().LoginPolicy.Query().Where(loginpolicy.IDEQ(typedReq.GetId())).Only(ctx)
		if err != nil {
			r.log.Errorf("get login_policy before delete failed: %s", err.Error())
			return nil, err
		}
		if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
			return nil, err
		}
		if err := r.entClient.Client().LoginPolicy.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete login_policy failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		entities, err := r.entClient.Client().LoginPolicy.Query().Where(loginpolicy.IDIn(typedReq.GetIds()...)).All(ctx)
		if err != nil {
			r.log.Errorf("list login_policys before delete failed: %s", err.Error())
			return nil, err
		}
		for _, entity := range entities {
			if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
				return nil, err
			}
		}
		if _, err := r.entClient.Client().LoginPolicy.Delete().Where(loginpolicy.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete login_policy failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
