// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.3.0 2026-06-18
// generated at: 2026-06-26 23:03:26 CST

package repo

import (
	auditv1 "admin/api/gen/audit/v1"

	ent "admin/internal/data/ent"

	"admin/internal/data/ent/operationauditlog"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	"strconv"

	"strings"

	"time"
)

type OperationAuditLogRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListOperationAuditLogResponse, error)

	Get(ctx context.Context, req *auditv1.GetOperationAuditLogRequest) (*auditv1.OperationAuditLog, error)
}

type operationAuditLogRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[auditv1.OperationAuditLog, ent.OperationAuditLog]

	repository *entCrud.Repository[
		ent.OperationAuditLogQuery, ent.OperationAuditLogSelect,
		ent.OperationAuditLogCreate, ent.OperationAuditLogCreateBulk,
		ent.OperationAuditLogUpdate, ent.OperationAuditLogUpdateOne,
		ent.OperationAuditLogDelete,
		predicate.OperationAuditLog,
		auditv1.OperationAuditLog, ent.OperationAuditLog,
	]
}

func NewOperationAuditLogRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *operationAuditLogRepo {
	repo := &operationAuditLogRepo{
		log:       ctx.NewLoggerHelper("operation_audit_log/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[auditv1.OperationAuditLog, ent.OperationAuditLog](),
	}

	repo.init()

	return repo
}

func (r *operationAuditLogRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.OperationAuditLogQuery, ent.OperationAuditLogSelect,
		ent.OperationAuditLogCreate, ent.OperationAuditLogCreateBulk,
		ent.OperationAuditLogUpdate, ent.OperationAuditLogUpdateOne,
		ent.OperationAuditLogDelete,
		predicate.OperationAuditLog,
		auditv1.OperationAuditLog, ent.OperationAuditLog,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func operationAuditLogEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func operationAuditLogFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func operationAuditLogParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *operationAuditLogRepo) applyGeneratedFilters(builder *ent.OperationAuditLogQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(operationauditlog.IDEQ(uint32(value)))
			}

		case "user_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid user_id filter value: %w", err)
				}
				builder.Where(operationauditlog.UserIDEQ(uint32(value)))
			}

		case "username":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.UsernameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.UsernameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.UsernameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.UsernameHasSuffix(condition.GetValue()))
			}

		case "resource_type":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.ResourceTypeEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.ResourceTypeContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.ResourceTypeHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.ResourceTypeHasSuffix(condition.GetValue()))
			}

		case "resource_id":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.ResourceIDEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.ResourceIDContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.ResourceIDHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.ResourceIDHasSuffix(condition.GetValue()))
			}

		case "action":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(operationauditlog.ActionEQ(operationauditlog.Action(condition.GetValue())))
			}

		case "before_data":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.BeforeDataEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.BeforeDataContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.BeforeDataHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.BeforeDataHasSuffix(condition.GetValue()))
			}

		case "after_data":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.AfterDataEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.AfterDataContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.AfterDataHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.AfterDataHasSuffix(condition.GetValue()))
			}

		case "sensitive_level":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(operationauditlog.SensitiveLevelEQ(operationauditlog.SensitiveLevel(condition.GetValue())))
			}

		case "request_id":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.RequestIDEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.RequestIDContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.RequestIDHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.RequestIDHasSuffix(condition.GetValue()))
			}

		case "trace_id":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.TraceIDEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.TraceIDContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.TraceIDHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.TraceIDHasSuffix(condition.GetValue()))
			}

		case "failure_reason":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.FailureReasonEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.FailureReasonContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.FailureReasonHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.FailureReasonHasSuffix(condition.GetValue()))
			}

		case "ip_address":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.IPAddressEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.IPAddressContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.IPAddressHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.IPAddressHasSuffix(condition.GetValue()))
			}

		case "log_hash":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(operationauditlog.LogHashEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(operationauditlog.LogHashContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(operationauditlog.LogHashHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(operationauditlog.LogHashHasSuffix(condition.GetValue()))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(operationauditlog.TenantIDEQ(uint32(value)))
			}

		case "created_at":

			value, err := operationAuditLogParseFilterTime(condition.GetValue(), "created_at")
			if err != nil {
				return err
			}
			switch condition.GetOp() {
			case paginationv1.Operator_GT:
				builder.Where(operationauditlog.CreatedAtGT(value))
			case paginationv1.Operator_GTE:
				builder.Where(operationauditlog.CreatedAtGTE(value))
			case paginationv1.Operator_LT:
				builder.Where(operationauditlog.CreatedAtLT(value))
			case paginationv1.Operator_LTE:
				builder.Where(operationauditlog.CreatedAtLTE(value))
			}

		}
	}

	return nil
}

func (r *operationAuditLogRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *operationAuditLogRepo) List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListOperationAuditLogResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	pagingReq := req
	var err error

	builder := r.entClient.Client().OperationAuditLog.Query()
	countBuilder := r.entClient.Client().OperationAuditLog.Query()
	if custom, ok := any(r).(interface {
		operationAuditLogRepoCustomList(context.Context, *ent.OperationAuditLogQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.operationAuditLogRepoCustomList(ctx, builder, pagingReq)
		if err != nil {
			return nil, err
		}
	}
	if custom, ok := any(r).(interface {
		operationAuditLogRepoCustomList(context.Context, *ent.OperationAuditLogQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.operationAuditLogRepoCustomList(ctx, countBuilder, pagingReq)
		if err != nil {
			return nil, err
		}
	}

	if err := r.applyGeneratedFilters(builder, pagingReq); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, pagingReq); err != nil {
		return nil, err
	}

	listReq := pagingReq
	if listReq == nil {
		listReq = &paginationv1.PagingRequest{}
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"created_at",
		paginationv1.Sorting_DESC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := listReq.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count operation_audit_log failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list operation_audit_log failed: %s", err.Error())
		return nil, err
	}

	items := make([]*auditv1.OperationAuditLog, 0, len(entities))
	if custom, ok := any(r).(interface {
		operationAuditLogEnrichListDTOs(context.Context, []*ent.OperationAuditLog) ([]*auditv1.OperationAuditLog, error)
	}); ok {
		items, err = custom.operationAuditLogEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &auditv1.ListOperationAuditLogResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *operationAuditLogRepo) Get(ctx context.Context, req *auditv1.GetOperationAuditLogRequest) (*auditv1.OperationAuditLog, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().OperationAuditLog.Query()
	entity, err := builder.Where(operationauditlog.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get operation_audit_log failed: %s", err.Error())
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		operationAuditLogEnrichGetDTO(context.Context, []*ent.OperationAuditLog) ([]*auditv1.OperationAuditLog, error)
	}); ok {
		items, err := custom.operationAuditLogEnrichGetDTO(ctx, []*ent.OperationAuditLog{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("operation_audit_log relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}
