// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-05-28 15:53:00 CST

package repo

import (
	auditv1 "admin/api/gen/audit/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/permissionauditlog"

	"admin/internal/data/ent/predicate"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	"strconv"

	"time"
)

type PermissionAuditLogRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListPermissionAuditLogResponse, error)

	Get(ctx context.Context, req *auditv1.GetPermissionAuditLogRequest) (*auditv1.PermissionAuditLog, error)
}

type permissionAuditLogRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[auditv1.PermissionAuditLog, ent.PermissionAuditLog]

	repository *entCrud.Repository[
		ent.PermissionAuditLogQuery, ent.PermissionAuditLogSelect,
		ent.PermissionAuditLogCreate, ent.PermissionAuditLogCreateBulk,
		ent.PermissionAuditLogUpdate, ent.PermissionAuditLogUpdateOne,
		ent.PermissionAuditLogDelete,
		predicate.PermissionAuditLog,
		auditv1.PermissionAuditLog, ent.PermissionAuditLog,
	]
}

func NewPermissionAuditLogRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *permissionAuditLogRepo {
	repo := &permissionAuditLogRepo{
		log:       ctx.NewLoggerHelper("permission_audit_log/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[auditv1.PermissionAuditLog, ent.PermissionAuditLog](),
	}

	repo.init()

	return repo
}

func (r *permissionAuditLogRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.PermissionAuditLogQuery, ent.PermissionAuditLogSelect,
		ent.PermissionAuditLogCreate, ent.PermissionAuditLogCreateBulk,
		ent.PermissionAuditLogUpdate, ent.PermissionAuditLogUpdateOne,
		ent.PermissionAuditLogDelete,
		predicate.PermissionAuditLog,
		auditv1.PermissionAuditLog, ent.PermissionAuditLog,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func permissionAuditLogEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func permissionAuditLogFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func (r *permissionAuditLogRepo) applyGeneratedFilters(builder *ent.PermissionAuditLogQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(permissionauditlog.IDEQ(uint32(value)))
			}

		case "operator_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid operator_id filter value: %w", err)
				}
				builder.Where(permissionauditlog.OperatorIDEQ(uint32(value)))
			}

		case "target_type":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.TargetTypeEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.TargetTypeContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.TargetTypeHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.TargetTypeHasSuffix(condition.GetValue()))
			}

		case "target_id":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.TargetIDEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.TargetIDContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.TargetIDHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.TargetIDHasSuffix(condition.GetValue()))
			}

		case "action":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(permissionauditlog.ActionEQ(permissionauditlog.Action(condition.GetValue())))
			}

		case "old_value":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.OldValueEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.OldValueContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.OldValueHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.OldValueHasSuffix(condition.GetValue()))
			}

		case "new_value":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.NewValueEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.NewValueContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.NewValueHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.NewValueHasSuffix(condition.GetValue()))
			}

		case "ip_address":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.IPAddressEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.IPAddressContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.IPAddressHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.IPAddressHasSuffix(condition.GetValue()))
			}

		case "request_id":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.RequestIDEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.RequestIDContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.RequestIDHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.RequestIDHasSuffix(condition.GetValue()))
			}

		case "reason":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.ReasonEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.ReasonContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.ReasonHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.ReasonHasSuffix(condition.GetValue()))
			}

		case "log_hash":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(permissionauditlog.LogHashEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(permissionauditlog.LogHashContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(permissionauditlog.LogHashHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(permissionauditlog.LogHashHasSuffix(condition.GetValue()))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(permissionauditlog.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *permissionAuditLogRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *permissionAuditLogRepo) List(ctx context.Context, req *v1.PagingRequest) (*auditv1.ListPermissionAuditLogResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().PermissionAuditLog.Query()
	countBuilder := r.entClient.Client().PermissionAuditLog.Query()

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"created_at",
		paginationv1.Sorting_DESC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count permission_audit_log failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list permission_audit_log failed: %s", err.Error())
		return nil, err
	}

	items := make([]*auditv1.PermissionAuditLog, 0, len(entities))
	if custom, ok := any(r).(interface {
		permissionAuditLogEnrichListDTOs(context.Context, []*ent.PermissionAuditLog) ([]*auditv1.PermissionAuditLog, error)
	}); ok {
		items, err = custom.permissionAuditLogEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &auditv1.ListPermissionAuditLogResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *permissionAuditLogRepo) Get(ctx context.Context, req *auditv1.GetPermissionAuditLogRequest) (*auditv1.PermissionAuditLog, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().PermissionAuditLog.Query()
	entity, err := builder.Where(permissionauditlog.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get permission_audit_log failed: %s", err.Error())
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		permissionAuditLogEnrichGetDTO(context.Context, []*ent.PermissionAuditLog) ([]*auditv1.PermissionAuditLog, error)
	}); ok {
		items, err := custom.permissionAuditLogEnrichGetDTO(ctx, []*ent.PermissionAuditLog{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("permission_audit_log relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}
