// Code generated by xkit.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 22:51:12 CST

package repo

import (
	"context"

	identityv1 "admin/api/gen/identity/v1"
	"admin/internal/data/ent"
)

func (r *positionRepo) enrichPositionTenantNamesWithContext(ctx context.Context, entities []*ent.Position) []*identityv1.Position {
	items := make([]*identityv1.Position, 0, len(entities))
	tenantIDs := make([]uint32, 0, len(entities))
	for _, entity := range entities {
		if entity == nil {
			continue
		}
		tenantIDs = append(tenantIDs, collectTenantIDs(entity.TenantID)...)
	}
	tenantNameMap := loadTenantNameMap(ctx, r.entClient.Client(), tenantIDs)
	for _, entity := range entities {
		if entity == nil {
			continue
		}
		dto := r.mapper.ToDTO(entity)
		if dto == nil {
			continue
		}
		dto.TenantName = tenantNameFromMap(tenantNameMap, entity.TenantID)
		items = append(items, dto)
	}
	return items
}

func (r *positionRepo) positionEnrichListDTOs(ctx context.Context, entities []*ent.Position) ([]*identityv1.Position, error) {
	return r.enrichPositionTenantNamesWithContext(ctx, entities), nil
}

func (r *positionRepo) positionEnrichGetDTO(ctx context.Context, entities []*ent.Position) ([]*identityv1.Position, error) {
	return r.enrichPositionTenantNamesWithContext(ctx, entities), nil
}
