// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-05-30 20:54:38 CST

package repo

import (
	permissionv1 "admin/api/gen/permission/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/predicate"

	"admin/internal/data/ent/role"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"time"
)

type RoleRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*permissionv1.ListRoleResponse, error)

	Get(ctx context.Context, req *permissionv1.GetRoleRequest) (*permissionv1.Role, error)

	Create(ctx context.Context, req *permissionv1.CreateRoleRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *permissionv1.UpdateRoleRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *permissionv1.DeleteRoleRequest) (*emptypb.Empty, error)
}

type roleRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[permissionv1.Role, ent.Role]

	repository *entCrud.Repository[
		ent.RoleQuery, ent.RoleSelect,
		ent.RoleCreate, ent.RoleCreateBulk,
		ent.RoleUpdate, ent.RoleUpdateOne,
		ent.RoleDelete,
		predicate.Role,
		permissionv1.Role, ent.Role,
	]
}

func NewRoleRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *roleRepo {
	repo := &roleRepo{
		log:       ctx.NewLoggerHelper("role/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[permissionv1.Role, ent.Role](),
	}

	repo.init()

	return repo
}

func (r *roleRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.RoleQuery, ent.RoleSelect,
		ent.RoleCreate, ent.RoleCreateBulk,
		ent.RoleUpdate, ent.RoleUpdateOne,
		ent.RoleDelete,
		predicate.Role,
		permissionv1.Role, ent.Role,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func roleEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func roleFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func (r *roleRepo) applyGeneratedFilters(builder *ent.RoleQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(role.IDEQ(uint32(value)))
			}

		case "name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(role.NameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(role.NameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(role.NameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(role.NameHasSuffix(condition.GetValue()))
			}

		case "code":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(role.CodeEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(role.CodeContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(role.CodeHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(role.CodeHasSuffix(condition.GetValue()))
			}

		case "type":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(role.TypeEQ(role.Type(condition.GetValue())))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(role.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(role.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(role.DeletedByEQ(uint32(value)))
			}

		case "remark":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(role.RemarkEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(role.RemarkContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(role.RemarkHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(role.RemarkHasSuffix(condition.GetValue()))
			}

		case "sort_order":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid sort_order filter value: %w", err)
				}
				builder.Where(role.SortOrderEQ(uint32(value)))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(role.TenantIDEQ(uint32(value)))
			}

		case "status":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(role.StatusEQ(role.Status(condition.GetValue())))
			}

		}
	}

	return nil
}

func (r *roleRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *roleRepo) List(ctx context.Context, req *v1.PagingRequest) (*permissionv1.ListRoleResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.roleQueryWithHybridTenantScope(ctx)
	countBuilder := r.roleQueryWithHybridTenantScope(ctx)

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(listReq.Sorting, "sort_order", paginationv1.Sorting_ASC)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}

	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count role failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list role failed: %s", err.Error())
		return nil, err
	}

	items, err := r.roleEnrichListDTOs(ctx, entities)
	if err != nil {
		return nil, err
	}
	return &permissionv1.ListRoleResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *roleRepo) Get(ctx context.Context, req *permissionv1.GetRoleRequest) (*permissionv1.Role, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	entity, err := r.entClient.Client().Role.Query().Where(role.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get role failed: %s", err.Error())
		return nil, err
	}
	if err := ensureHybridTenantAccessible(ctx, entity.TenantID); err != nil {
		return nil, err
	}

	items, err := r.roleEnrichGetDTO(ctx, []*ent.Role{entity})
	if err != nil {
		return nil, err
	}
	if len(items) == 0 {
		return nil, fmt.Errorf("role relation hydration returned no result")
	}
	return items[0], nil

}

// Create is generated from the source proto contract.
func (r *roleRepo) Create(ctx context.Context, req *permissionv1.CreateRoleRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		roleCustomCreate(ctx context.Context, req *permissionv1.CreateRoleRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.roleCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().Role.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetNillableName(req.Data.Name)
	builder.SetNillableCode(req.Data.Code)
	builder.SetIsProtected(req.Data.GetIsProtected())
	builder.SetType(role.Type(req.Data.GetType().String()))
	builder.SetNillableSortOrder(req.Data.SortOrder)
	builder.SetNillableTenantID(req.Data.TenantId)
	builder.SetStatus(role.Status(req.Data.GetStatus().String()))
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert role failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *roleRepo) Update(ctx context.Context, req *permissionv1.UpdateRoleRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		roleCustomUpdate(ctx context.Context, req *permissionv1.UpdateRoleRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.roleCustomUpdate(ctx, req)
	}
	builder := r.entClient.Client().Role.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	if req.Data.Name != nil {
		builder.SetNillableName(req.Data.Name)
	} else if req.GetUpdateMask() != nil && roleFieldMaskContains(req.GetUpdateMask().GetPaths(), "name") {
		builder.ClearName()
	}
	if req.Data.Code != nil {
		builder.SetNillableCode(req.Data.Code)
	} else if req.GetUpdateMask() != nil && roleFieldMaskContains(req.GetUpdateMask().GetPaths(), "code") {
		builder.ClearCode()
	}
	builder.SetIsProtected(req.Data.GetIsProtected())
	builder.SetType(role.Type(req.Data.GetType().String()))
	if req.Data.SortOrder != nil {
		builder.SetNillableSortOrder(req.Data.SortOrder)
	} else if req.GetUpdateMask() != nil && roleFieldMaskContains(req.GetUpdateMask().GetPaths(), "sort_order", "sortOrder") {
		builder.ClearSortOrder()
	}
	builder.SetStatus(role.Status(req.Data.GetStatus().String()))
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update role failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *roleRepo) Delete(ctx context.Context, req *permissionv1.DeleteRoleRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		roleCustomDelete(ctx context.Context, req *permissionv1.DeleteRoleRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.roleCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		if err := r.entClient.Client().Role.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete role failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		if _, err := r.entClient.Client().Role.Delete().Where(role.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete role failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
