// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 18:41:15 CST

package repo

import (
	taskv1 "admin/api/gen/task/v1"

	"admin/internal/data/ent"

	"admin/internal/data/ent/predicate"

	"admin/internal/data/ent/tasklog"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	"strconv"

	"time"
)

type TaskLogRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*taskv1.ListTaskLogResponse, error)

	Get(ctx context.Context, req *taskv1.GetTaskLogRequest) (*taskv1.TaskLog, error)

	Delete(ctx context.Context, req *taskv1.DeleteTaskLogRequest) (*emptypb.Empty, error)
}

type taskLogRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[taskv1.TaskLog, ent.TaskLog]

	repository *entCrud.Repository[
		ent.TaskLogQuery, ent.TaskLogSelect,
		ent.TaskLogCreate, ent.TaskLogCreateBulk,
		ent.TaskLogUpdate, ent.TaskLogUpdateOne,
		ent.TaskLogDelete,
		predicate.TaskLog,
		taskv1.TaskLog, ent.TaskLog,
	]
}

func NewTaskLogRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *taskLogRepo {
	repo := &taskLogRepo{
		log:       ctx.NewLoggerHelper("task_log/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[taskv1.TaskLog, ent.TaskLog](),
	}

	repo.init()

	return repo
}

func (r *taskLogRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.TaskLogQuery, ent.TaskLogSelect,
		ent.TaskLogCreate, ent.TaskLogCreateBulk,
		ent.TaskLogUpdate, ent.TaskLogUpdateOne,
		ent.TaskLogDelete,
		predicate.TaskLog,
		taskv1.TaskLog, ent.TaskLog,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func taskLogEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func taskLogTimePtrFromProto(value *timestamppb.Timestamp) *time.Time {
	if value == nil {
		return nil
	}
	out := value.AsTime()
	return &out
}

func taskLogFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func (r *taskLogRepo) applyGeneratedFilters(builder *ent.TaskLogQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 64)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(tasklog.IDEQ(uint64(value)))
			}

		case "task_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 64)
				if err != nil {
					return fmt.Errorf("invalid task_id filter value: %w", err)
				}
				builder.Where(tasklog.TaskIDEQ(uint64(value)))
			}

		case "input":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(tasklog.InputEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(tasklog.InputContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(tasklog.InputHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(tasklog.InputHasSuffix(condition.GetValue()))
			}

		case "output":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(tasklog.OutputEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(tasklog.OutputContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(tasklog.OutputHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(tasklog.OutputHasSuffix(condition.GetValue()))
			}

		case "error":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(tasklog.ErrorEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(tasklog.ErrorContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(tasklog.ErrorHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(tasklog.ErrorHasSuffix(condition.GetValue()))
			}

		case "status":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(tasklog.StatusEQ(tasklog.Status(condition.GetValue())))
			}

		case "process_time":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid process_time filter value: %w", err)
				}
				builder.Where(tasklog.ProcessTimeEQ(uint32(value)))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(tasklog.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

// List is generated from the source proto contract.
func (r *taskLogRepo) List(ctx context.Context, req *v1.PagingRequest) (*taskv1.ListTaskLogResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().TaskLog.Query()
	countBuilder := r.entClient.Client().TaskLog.Query()

	if err := r.applyGeneratedFilters(builder, req); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, req); err != nil {
		return nil, err
	}

	listReq := &v1.PagingRequest{
		Page:      req.Page,
		PageSize:  req.PageSize,
		Offset:    req.Offset,
		Limit:     req.Limit,
		Token:     req.Token,
		NoPaging:  req.NoPaging,
		OrderBy:   req.OrderBy,
		Sorting:   req.Sorting,
		FieldMask: req.FieldMask,
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"id",
		paginationv1.Sorting_DESC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := req.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count task_log failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list task_log failed: %s", err.Error())
		return nil, err
	}

	items := make([]*taskv1.TaskLog, 0, len(entities))
	if custom, ok := any(r).(interface {
		taskLogEnrichListDTOs(context.Context, []*ent.TaskLog) ([]*taskv1.TaskLog, error)
	}); ok {
		items, err = custom.taskLogEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &taskv1.ListTaskLogResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *taskLogRepo) Get(ctx context.Context, req *taskv1.GetTaskLogRequest) (*taskv1.TaskLog, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().TaskLog.Query()
	entity, err := builder.Where(tasklog.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get task_log failed: %s", err.Error())
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		taskLogEnrichGetDTO(context.Context, []*ent.TaskLog) ([]*taskv1.TaskLog, error)
	}); ok {
		items, err := custom.taskLogEnrichGetDTO(ctx, []*ent.TaskLog{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("task_log relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Delete is generated from the source proto contract.
func (r *taskLogRepo) Delete(ctx context.Context, req *taskv1.DeleteTaskLogRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		taskLogCustomDelete(ctx context.Context, req *taskv1.DeleteTaskLogRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.taskLogCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint64 }:
		if err := r.entClient.Client().TaskLog.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete task_log failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint64 }:
		if _, err := r.entClient.Client().TaskLog.Delete().Where(tasklog.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete task_log failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
