// Code generated by xkit.
// xkit version: v0.2.0 2026-05-28
// generated at: 2026-06-03 22:51:12 CST

package repo

import (
	"context"
	"fmt"

	taskv1 "admin/api/gen/task/v1"
	"admin/internal/data/ent/task"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Add TaskRepo-specific query helpers and hand-written data access code here.
// This file is created once and is never overwritten by xkit.

type TaskRuntimeRepo interface {
	ListTasksByGroupID(ctx context.Context, groupID uint64) ([]*taskv1.Task, error)
	UpdateTaskRuntimeState(ctx context.Context, taskID uint64, status taskv1.Task_Status, entryID *uint32) error
}

func (r *taskRepo) ListTasksByGroupID(ctx context.Context, groupID uint64) ([]*taskv1.Task, error) {
	entities, err := r.entClient.Client().Task.Query().
		Where(task.GroupIDEQ(groupID)).
		Order(task.ByID()).
		All(ctx)
	if err != nil {
		r.log.Errorf("list task by group failed: %s", err.Error())
		return nil, err
	}

	items := make([]*taskv1.Task, 0, len(entities))
	for _, entity := range entities {
		if entity == nil {
			continue
		}
		items = append(items, r.mapper.ToDTO(entity))
	}
	return items, nil
}

func (r *taskRepo) UpdateTaskRuntimeState(ctx context.Context, taskID uint64, status taskv1.Task_Status, entryID *uint32) error {
	if taskID == 0 {
		return fmt.Errorf("invalid task id")
	}

	now, viewer := r.generatedAuditContext(ctx)
	builder := r.entClient.Client().Task.UpdateOneID(taskID).
		SetStatus(task.Status(status.String())).
		SetUpdatedAt(now).
		SetUpdatedBy(uint32(viewer.UserID()))
	if entryID != nil {
		builder.SetEntryID(*entryID)
	} else {
		builder.ClearEntryID()
	}

	if _, err := builder.Save(ctx); err != nil {
		r.log.Errorf("update task runtime state failed: %s", err.Error())
		return err
	}
	return nil
}

func (r *taskRepo) taskCustomUpdate(ctx context.Context, req *taskv1.UpdateTaskRequest) (*emptypb.Empty, error) {
	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	current, err := r.entClient.Client().Task.Query().Where(task.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("load task failed: %s", err.Error())
		return nil, err
	}
	if err := ensureHybridTenantAccessible(ctx, current.TenantID); err != nil {
		return nil, err
	}

	builder := r.entClient.Client().Task.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetTaskName(req.Data.GetTaskName())
	builder.SetGroupID(req.Data.GetGroupId())
	builder.SetTaskType(task.TaskType(req.Data.GetTaskType().String()))
	if req.Data.CronExpression != nil {
		builder.SetNillableCronExpression(req.Data.CronExpression)
	} else if req.GetUpdateMask() != nil && taskFieldMaskContains(req.GetUpdateMask().GetPaths(), "cron_expression", "cronExpression") {
		builder.ClearCronExpression()
	}
	if req.Data.InvokeTarget != nil {
		builder.SetNillableInvokeTarget(req.Data.InvokeTarget)
	} else if req.GetUpdateMask() != nil && taskFieldMaskContains(req.GetUpdateMask().GetPaths(), "invoke_target", "invokeTarget") {
		builder.ClearInvokeTarget()
	}
	if req.Data.Args != nil {
		builder.SetNillableArgs(req.Data.Args)
	} else if req.GetUpdateMask() != nil && taskFieldMaskContains(req.GetUpdateMask().GetPaths(), "args") {
		builder.ClearArgs()
	}
	builder.SetRetry(req.Data.GetRetry())
	builder.SetConcurrent(req.Data.GetConcurrent())
	if req.Data.EntryId != nil {
		builder.SetNillableEntryID(req.Data.EntryId)
	} else if req.GetUpdateMask() != nil && taskFieldMaskContains(req.GetUpdateMask().GetPaths(), "entry_id", "entryId") {
		builder.ClearEntryID()
	}
	builder.SetStatus(task.Status(req.Data.GetStatus().String()))
	if req.Data.Remark != nil {
		builder.SetNillableRemark(req.Data.Remark)
	} else if req.GetUpdateMask() != nil && taskFieldMaskContains(req.GetUpdateMask().GetPaths(), "remark") {
		builder.ClearRemark()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update task failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return &emptypb.Empty{}, nil
}
