// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.3.0 2026-06-18
// generated at: 2026-06-26 23:03:27 CST

package repo

import (
	taskv1 "admin/api/gen/task/v1"

	ent "admin/internal/data/ent"

	"admin/internal/data/ent/predicate"

	"admin/internal/data/ent/taskgroup"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	"strconv"

	"strings"

	"time"
)

type TaskGroupRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*taskv1.ListTaskGroupResponse, error)

	Get(ctx context.Context, req *taskv1.GetTaskGroupRequest) (*taskv1.TaskGroup, error)

	Create(ctx context.Context, req *taskv1.CreateTaskGroupRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *taskv1.UpdateTaskGroupRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *taskv1.DeleteTaskGroupRequest) (*emptypb.Empty, error)
}

type taskGroupRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[taskv1.TaskGroup, ent.TaskGroup]

	repository *entCrud.Repository[
		ent.TaskGroupQuery, ent.TaskGroupSelect,
		ent.TaskGroupCreate, ent.TaskGroupCreateBulk,
		ent.TaskGroupUpdate, ent.TaskGroupUpdateOne,
		ent.TaskGroupDelete,
		predicate.TaskGroup,
		taskv1.TaskGroup, ent.TaskGroup,
	]
}

func NewTaskGroupRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *taskGroupRepo {
	repo := &taskGroupRepo{
		log:       ctx.NewLoggerHelper("task_group/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[taskv1.TaskGroup, ent.TaskGroup](),
	}

	repo.init()

	return repo
}

func (r *taskGroupRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.TaskGroupQuery, ent.TaskGroupSelect,
		ent.TaskGroupCreate, ent.TaskGroupCreateBulk,
		ent.TaskGroupUpdate, ent.TaskGroupUpdateOne,
		ent.TaskGroupDelete,
		predicate.TaskGroup,
		taskv1.TaskGroup, ent.TaskGroup,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func taskGroupFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func taskGroupParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *taskGroupRepo) applyGeneratedFilters(builder *ent.TaskGroupQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 64)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(taskgroup.IDEQ(uint64(value)))
			}

		case "group_name":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(taskgroup.GroupNameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(taskgroup.GroupNameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(taskgroup.GroupNameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(taskgroup.GroupNameHasSuffix(condition.GetValue()))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(taskgroup.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(taskgroup.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(taskgroup.DeletedByEQ(uint32(value)))
			}

		case "remark":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(taskgroup.RemarkEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(taskgroup.RemarkContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(taskgroup.RemarkHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(taskgroup.RemarkHasSuffix(condition.GetValue()))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(taskgroup.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *taskGroupRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *taskGroupRepo) List(ctx context.Context, req *v1.PagingRequest) (*taskv1.ListTaskGroupResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	pagingReq := req
	var err error

	builder := r.entClient.Client().TaskGroup.Query()
	countBuilder := r.entClient.Client().TaskGroup.Query()
	if custom, ok := any(r).(interface {
		taskGroupRepoCustomList(context.Context, *ent.TaskGroupQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.taskGroupRepoCustomList(ctx, builder, pagingReq)
		if err != nil {
			return nil, err
		}
	}
	if custom, ok := any(r).(interface {
		taskGroupRepoCustomList(context.Context, *ent.TaskGroupQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.taskGroupRepoCustomList(ctx, countBuilder, pagingReq)
		if err != nil {
			return nil, err
		}
	}

	if err := r.applyGeneratedFilters(builder, pagingReq); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, pagingReq); err != nil {
		return nil, err
	}

	listReq := pagingReq
	if listReq == nil {
		listReq = &paginationv1.PagingRequest{}
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"id",
		paginationv1.Sorting_DESC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := listReq.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count task_group failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list task_group failed: %s", err.Error())
		return nil, err
	}

	items := make([]*taskv1.TaskGroup, 0, len(entities))
	if custom, ok := any(r).(interface {
		taskGroupEnrichListDTOs(context.Context, []*ent.TaskGroup) ([]*taskv1.TaskGroup, error)
	}); ok {
		items, err = custom.taskGroupEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &taskv1.ListTaskGroupResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *taskGroupRepo) Get(ctx context.Context, req *taskv1.GetTaskGroupRequest) (*taskv1.TaskGroup, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().TaskGroup.Query()
	entity, err := builder.Where(taskgroup.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get task_group failed: %s", err.Error())
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		taskGroupEnrichGetDTO(context.Context, []*ent.TaskGroup) ([]*taskv1.TaskGroup, error)
	}); ok {
		items, err := custom.taskGroupEnrichGetDTO(ctx, []*ent.TaskGroup{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("task_group relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *taskGroupRepo) Create(ctx context.Context, req *taskv1.CreateTaskGroupRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		taskGroupCustomCreate(ctx context.Context, req *taskv1.CreateTaskGroupRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.taskGroupCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().TaskGroup.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetGroupName(req.Data.GetGroupName())
	builder.SetNillableRemark(req.Data.Remark)
	builder.SetNillableTenantID(req.Data.TenantId)
	builder.SetCreatedAt(now)
	builder.SetCreatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert task_group failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *taskGroupRepo) Update(ctx context.Context, req *taskv1.UpdateTaskGroupRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		taskGroupCustomUpdate(ctx context.Context, req *taskv1.UpdateTaskGroupRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.taskGroupCustomUpdate(ctx, req)
	}
	builder := r.entClient.Client().TaskGroup.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetGroupName(req.Data.GetGroupName())
	if req.Data.Remark != nil {
		builder.SetNillableRemark(req.Data.Remark)
	} else if req.GetUpdateMask() != nil && taskGroupFieldMaskContains(req.GetUpdateMask().GetPaths(), "remark") {
		builder.ClearRemark()
	}
	builder.SetUpdatedAt(now)
	builder.SetUpdatedBy(uint32(viewer.UserID()))

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update task_group failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *taskGroupRepo) Delete(ctx context.Context, req *taskv1.DeleteTaskGroupRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		taskGroupCustomDelete(ctx context.Context, req *taskv1.DeleteTaskGroupRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.taskGroupCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint64 }:
		if err := r.entClient.Client().TaskGroup.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete task_group failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint64 }:
		if _, err := r.entClient.Client().TaskGroup.Delete().Where(taskgroup.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete task_group failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}
