// Code generated by codex.
// generated at: 2026-05-30 20:54:38 CST

package repo

// Add TaskRepo-specific query helpers and hand-written data access code here.
// This file is created once and is never overwritten by xkit.
