// Code generated by xkit. DO NOT EDIT.
// xkit version: v0.3.0 2026-06-18
// generated at: 2026-06-26 23:03:27 CST

package repo

import (
	identityv1 "admin/api/gen/identity/v1"

	ent "admin/internal/data/ent"

	"admin/internal/data/ent/predicate"

	"admin/internal/data/ent/user"

	"context"

	"fmt"

	paginationv1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	v1 "github.com/chnxq/x-crud/api/gen/pagination/v1"

	entCrud "github.com/chnxq/x-crud/entgo"

	crudviewer "github.com/chnxq/x-crud/viewer"

	"github.com/chnxq/x-utils/copierutil"

	"github.com/chnxq/x-utils/mapper"

	"github.com/chnxq/xkitmod/log"

	"github.com/chnxq/xkitpkg/app"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	"strconv"

	"strings"

	"time"
)

type UserRepo interface {
	List(ctx context.Context, req *v1.PagingRequest) (*identityv1.ListUserResponse, error)

	Get(ctx context.Context, req *identityv1.GetUserRequest) (*identityv1.User, error)

	Create(ctx context.Context, req *identityv1.CreateUserRequest) (*emptypb.Empty, error)

	Update(ctx context.Context, req *identityv1.UpdateUserRequest) (*emptypb.Empty, error)

	Delete(ctx context.Context, req *identityv1.DeleteUserRequest) (*emptypb.Empty, error)

	UserExists(ctx context.Context, req *identityv1.UserExistsRequest) (*identityv1.UserExistsResponse, error)
}

type userRepo struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[identityv1.User, ent.User]

	repository *entCrud.Repository[
		ent.UserQuery, ent.UserSelect,
		ent.UserCreate, ent.UserCreateBulk,
		ent.UserUpdate, ent.UserUpdateOne,
		ent.UserDelete,
		predicate.User,
		identityv1.User, ent.User,
	]
}

func NewUserRepo(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *userRepo {
	repo := &userRepo{
		log:       ctx.NewLoggerHelper("user/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[identityv1.User, ent.User](),
	}

	repo.init()

	return repo
}

func (r *userRepo) init() {
	r.repository = entCrud.NewRepository[
		ent.UserQuery, ent.UserSelect,
		ent.UserCreate, ent.UserCreateBulk,
		ent.UserUpdate, ent.UserUpdateOne,
		ent.UserDelete,
		predicate.User,
		identityv1.User, ent.User,
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

func userEnumPtrFromProto[T ~string, P interface{ String() string }](value *P) *T {
	if value == nil {
		return nil
	}
	out := T((*value).String())
	return &out
}

func userTimePtrFromProto(value *timestamppb.Timestamp) *time.Time {
	if value == nil {
		return nil
	}
	out := value.AsTime()
	return &out
}

func userFieldMaskContains(paths []string, candidates ...string) bool {
	for _, path := range paths {
		for _, candidate := range candidates {
			if path == candidate {
				return true
			}
		}
	}
	return false
}

func userParseFilterTime(value, field string) (time.Time, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Time{}, fmt.Errorf("invalid %s filter value: empty", field)
	}

	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(layout, trimmed); err == nil {
			return parsed, nil
		}
	}

	return time.Time{}, fmt.Errorf("invalid %s filter value: %q", field, value)
}

func (r *userRepo) applyGeneratedFilters(builder *ent.UserQuery, req *paginationv1.PagingRequest) error {
	if req == nil || req.GetFilterExpr() == nil {
		return nil
	}

	for _, condition := range req.GetFilterExpr().GetConditions() {
		if condition == nil {
			continue
		}
		switch condition.GetField() {

		case "id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid id filter value: %w", err)
				}
				builder.Where(user.IDEQ(uint32(value)))
			}

		case "username":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.UsernameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.UsernameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.UsernameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.UsernameHasSuffix(condition.GetValue()))
			}

		case "nickname":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.NicknameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.NicknameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.NicknameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.NicknameHasSuffix(condition.GetValue()))
			}

		case "realname":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.RealnameEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.RealnameContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.RealnameHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.RealnameHasSuffix(condition.GetValue()))
			}

		case "email":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.EmailEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.EmailContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.EmailHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.EmailHasSuffix(condition.GetValue()))
			}

		case "mobile":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.MobileEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.MobileContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.MobileHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.MobileHasSuffix(condition.GetValue()))
			}

		case "telephone":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.TelephoneEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.TelephoneContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.TelephoneHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.TelephoneHasSuffix(condition.GetValue()))
			}

		case "avatar":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.AvatarEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.AvatarContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.AvatarHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.AvatarHasSuffix(condition.GetValue()))
			}

		case "address":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.AddressEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.AddressContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.AddressHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.AddressHasSuffix(condition.GetValue()))
			}

		case "region":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.RegionEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.RegionContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.RegionHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.RegionHasSuffix(condition.GetValue()))
			}

		case "description":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.DescriptionEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.DescriptionContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.DescriptionHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.DescriptionHasSuffix(condition.GetValue()))
			}

		case "gender":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(user.GenderEQ(user.Gender(condition.GetValue())))
			}

		case "last_login_ip":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.LastLoginIPEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.LastLoginIPContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.LastLoginIPHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.LastLoginIPHasSuffix(condition.GetValue()))
			}

		case "status":

			if condition.GetOp() == paginationv1.Operator_EQ {
				builder.Where(user.StatusEQ(user.Status(condition.GetValue())))
			}

		case "created_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid created_by filter value: %w", err)
				}
				builder.Where(user.CreatedByEQ(uint32(value)))
			}

		case "updated_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid updated_by filter value: %w", err)
				}
				builder.Where(user.UpdatedByEQ(uint32(value)))
			}

		case "deleted_by":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid deleted_by filter value: %w", err)
				}
				builder.Where(user.DeletedByEQ(uint32(value)))
			}

		case "remark":

			switch condition.GetOp() {
			case paginationv1.Operator_EQ:
				builder.Where(user.RemarkEQ(condition.GetValue()))
			case paginationv1.Operator_CONTAINS:
				builder.Where(user.RemarkContains(condition.GetValue()))
			case paginationv1.Operator_STARTS_WITH:
				builder.Where(user.RemarkHasPrefix(condition.GetValue()))
			case paginationv1.Operator_ENDS_WITH:
				builder.Where(user.RemarkHasSuffix(condition.GetValue()))
			}

		case "tenant_id":

			if condition.GetOp() == paginationv1.Operator_EQ {
				value, err := strconv.ParseUint(condition.GetValue(), 10, 32)
				if err != nil {
					return fmt.Errorf("invalid tenant_id filter value: %w", err)
				}
				builder.Where(user.TenantIDEQ(uint32(value)))
			}

		}
	}

	return nil
}

func (r *userRepo) generatedAuditContext(ctx context.Context) (time.Time, crudviewer.Context) {
	viewer := crudviewer.MustFromContext(ctx)
	return time.Now(), viewer
}

// List is generated from the source proto contract.
func (r *userRepo) List(ctx context.Context, req *v1.PagingRequest) (*identityv1.ListUserResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	pagingReq := req
	var err error

	builder := r.entClient.Client().User.Query()
	countBuilder := r.entClient.Client().User.Query()
	if tenantID := viewerTenantID(ctx); tenantID != nil {
		builder.Where(user.TenantIDEQ(*tenantID))
		countBuilder.Where(user.TenantIDEQ(*tenantID))
	}
	if custom, ok := any(r).(interface {
		userRepoCustomList(context.Context, *ent.UserQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.userRepoCustomList(ctx, builder, pagingReq)
		if err != nil {
			return nil, err
		}
	}
	if custom, ok := any(r).(interface {
		userRepoCustomList(context.Context, *ent.UserQuery, *paginationv1.PagingRequest) (*paginationv1.PagingRequest, error)
	}); ok {
		pagingReq, err = custom.userRepoCustomList(ctx, countBuilder, pagingReq)
		if err != nil {
			return nil, err
		}
	}

	if err := r.applyGeneratedFilters(builder, pagingReq); err != nil {
		return nil, err
	}
	if err := r.applyGeneratedFilters(countBuilder, pagingReq); err != nil {
		return nil, err
	}

	listReq := pagingReq
	if listReq == nil {
		listReq = &paginationv1.PagingRequest{}
	}
	listReq.Sorting = withDefaultSorting(
		listReq.Sorting,
		"id",
		paginationv1.Sorting_ASC,
	)
	if listReq.Page == nil && listReq.PageSize == nil && listReq.Offset == nil && listReq.Limit == nil && !listReq.GetNoPaging() {
		limit := uint32(20)
		offset := listReq.GetOffset()
		listReq.Limit = &limit
		listReq.Offset = &offset
	}
	if _, _, err := r.repository.BuildListSelectorWithPaging(builder, listReq); err != nil {
		return nil, err
	}
	total, err := countBuilder.Count(ctx)
	if err != nil {
		r.log.Errorf("count user failed: %s", err.Error())
		return nil, err
	}
	entities, err := builder.All(ctx)
	if err != nil {
		r.log.Errorf("list user failed: %s", err.Error())
		return nil, err
	}

	items := make([]*identityv1.User, 0, len(entities))
	if custom, ok := any(r).(interface {
		userEnrichListDTOs(context.Context, []*ent.User) ([]*identityv1.User, error)
	}); ok {
		items, err = custom.userEnrichListDTOs(ctx, entities)
		if err != nil {
			return nil, err
		}
	} else {
		for _, entity := range entities {
			items = append(items, r.mapper.ToDTO(entity))
		}
	}

	return &identityv1.ListUserResponse{Total: uint64(total), Items: items}, nil

}

// Get is generated from the source proto contract.
func (r *userRepo) Get(ctx context.Context, req *identityv1.GetUserRequest) (*identityv1.User, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().User.Query()
	switch req.GetQueryBy().(type) {
	case *identityv1.GetUserRequest_Id:
		builder.Where(user.IDEQ(req.GetId()))
	case *identityv1.GetUserRequest_Username:
		builder.Where(user.UsernameEQ(req.GetUsername()))
	default:
		return nil, fmt.Errorf("invalid query by type")
	}

	entity, err := builder.Only(ctx)
	if err != nil {
		if !ent.IsNotFound(err) {
			r.log.Errorf("get user failed: %s", err.Error())
		}
		return nil, err
	}
	if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
		return nil, err
	}

	dto := r.mapper.ToDTO(entity)
	if custom, ok := any(r).(interface {
		userEnrichGetDTO(context.Context, []*ent.User) ([]*identityv1.User, error)
	}); ok {
		items, err := custom.userEnrichGetDTO(ctx, []*ent.User{entity})
		if err != nil {
			return nil, err
		}
		if len(items) == 0 {
			return nil, fmt.Errorf("user relation hydration returned no result")
		}
		dto = items[0]
	}

	return dto, nil

}

// Create is generated from the source proto contract.
func (r *userRepo) Create(ctx context.Context, req *identityv1.CreateUserRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		userCustomCreate(ctx context.Context, req *identityv1.CreateUserRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.userCustomCreate(ctx, req)
	}

	builder := r.entClient.Client().User.Create()
	now, viewer := r.generatedAuditContext(ctx)
	builder.SetNillableUsername(req.Data.Username)
	builder.SetNillableNickname(req.Data.Nickname)
	builder.SetNillableRealname(req.Data.Realname)
	builder.SetNillableEmail(req.Data.Email)
	builder.SetNillableMobile(req.Data.Mobile)
	builder.SetNillableTelephone(req.Data.Telephone)
	builder.SetNillableAvatar(req.Data.Avatar)
	builder.SetNillableAddress(req.Data.Address)
	builder.SetNillableRegion(req.Data.Region)
	builder.SetNillableDescription(req.Data.Description)
	builder.SetNillableGender(userEnumPtrFromProto[user.Gender](req.Data.Gender))
	builder.SetNillableLastLoginAt(userTimePtrFromProto(req.Data.LastLoginAt))
	builder.SetNillableLastLoginIP(req.Data.LastLoginIp)
	builder.SetNillableLockedUntil(userTimePtrFromProto(req.Data.LockedUntil))
	builder.SetNillableStatus(userEnumPtrFromProto[user.Status](req.Data.Status))
	builder.SetNillableRemark(req.Data.Remark)
	tenantID, err := resolveCreateTenantID(ctx, req.Data.TenantId)
	if err != nil {
		return nil, err
	}
	builder.SetNillableTenantID(tenantID)
	builder.SetCreatedBy(uint32(viewer.UserID()))
	builder.SetCreatedAt(now)

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert user failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Update is generated from the source proto contract.
func (r *userRepo) Update(ctx context.Context, req *identityv1.UpdateUserRequest) (*emptypb.Empty, error) {

	if req == nil || req.Data == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		userCustomUpdate(ctx context.Context, req *identityv1.UpdateUserRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.userCustomUpdate(ctx, req)
	}
	current, err := r.entClient.Client().User.Query().Where(user.IDEQ(req.GetId())).Only(ctx)
	if err != nil {
		r.log.Errorf("get user before update failed: %s", err.Error())
		return nil, err
	}
	if err := ensureTenantAccessible(ctx, current.TenantID); err != nil {
		return nil, err
	}
	builder := r.entClient.Client().User.UpdateOneID(req.GetId())
	now, viewer := r.generatedAuditContext(ctx)
	if req.Data.Nickname != nil {
		builder.SetNillableNickname(req.Data.Nickname)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "nickname") {
		builder.ClearNickname()
	}
	if req.Data.Realname != nil {
		builder.SetNillableRealname(req.Data.Realname)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "realname") {
		builder.ClearRealname()
	}
	if req.Data.Email != nil {
		builder.SetNillableEmail(req.Data.Email)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "email") {
		builder.ClearEmail()
	}
	if req.Data.Mobile != nil {
		builder.SetNillableMobile(req.Data.Mobile)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "mobile") {
		builder.ClearMobile()
	}
	if req.Data.Telephone != nil {
		builder.SetNillableTelephone(req.Data.Telephone)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "telephone") {
		builder.ClearTelephone()
	}
	if req.Data.Avatar != nil {
		builder.SetNillableAvatar(req.Data.Avatar)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "avatar") {
		builder.ClearAvatar()
	}
	if req.Data.Address != nil {
		builder.SetNillableAddress(req.Data.Address)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "address") {
		builder.ClearAddress()
	}
	if req.Data.Region != nil {
		builder.SetNillableRegion(req.Data.Region)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "region") {
		builder.ClearRegion()
	}
	if req.Data.Description != nil {
		builder.SetNillableDescription(req.Data.Description)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "description") {
		builder.ClearDescription()
	}
	if req.Data.Gender != nil {
		builder.SetNillableGender(userEnumPtrFromProto[user.Gender](req.Data.Gender))
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "gender") {
		builder.ClearGender()
	}
	if req.Data.LastLoginAt != nil {
		builder.SetNillableLastLoginAt(userTimePtrFromProto(req.Data.LastLoginAt))
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "last_login_at", "lastLoginAt") {
		builder.ClearLastLoginAt()
	}
	if req.Data.LastLoginIp != nil {
		builder.SetNillableLastLoginIP(req.Data.LastLoginIp)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "last_login_ip", "lastLoginIp") {
		builder.ClearLastLoginIP()
	}
	if req.Data.LockedUntil != nil {
		builder.SetNillableLockedUntil(userTimePtrFromProto(req.Data.LockedUntil))
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "locked_until", "lockedUntil") {
		builder.ClearLockedUntil()
	}
	if req.Data.Status != nil {
		builder.SetNillableStatus(userEnumPtrFromProto[user.Status](req.Data.Status))
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "status") {
		builder.ClearStatus()
	}
	if req.Data.Remark != nil {
		builder.SetNillableRemark(req.Data.Remark)
	} else if req.GetUpdateMask() != nil && userFieldMaskContains(req.GetUpdateMask().GetPaths(), "remark") {
		builder.ClearRemark()
	}
	builder.SetUpdatedBy(uint32(viewer.UserID()))
	builder.SetUpdatedAt(now)

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update user failed: %s", err.Error())
		return nil, err
	}

	_ = entity
	return nil, nil

}

// Delete is generated from the source proto contract.
func (r *userRepo) Delete(ctx context.Context, req *identityv1.DeleteUserRequest) (*emptypb.Empty, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}
	if custom, ok := any(r).(interface {
		userCustomDelete(ctx context.Context, req *identityv1.DeleteUserRequest) (*emptypb.Empty, error)
	}); ok {
		return custom.userCustomDelete(ctx, req)
	}

	switch typedReq := any(req).(type) {
	case interface{ GetId() uint32 }:
		entity, err := r.entClient.Client().User.Query().Where(user.IDEQ(typedReq.GetId())).Only(ctx)
		if err != nil {
			r.log.Errorf("get user before delete failed: %s", err.Error())
			return nil, err
		}
		if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
			return nil, err
		}
		if err := r.entClient.Client().User.DeleteOneID(typedReq.GetId()).Exec(ctx); err != nil {
			r.log.Errorf("delete user failed: %s", err.Error())
			return nil, err
		}
	case interface{ GetIds() []uint32 }:
		entities, err := r.entClient.Client().User.Query().Where(user.IDIn(typedReq.GetIds()...)).All(ctx)
		if err != nil {
			r.log.Errorf("list users before delete failed: %s", err.Error())
			return nil, err
		}
		for _, entity := range entities {
			if err := ensureTenantAccessible(ctx, entity.TenantID); err != nil {
				return nil, err
			}
		}
		if _, err := r.entClient.Client().User.Delete().Where(user.IDIn(typedReq.GetIds()...)).Exec(ctx); err != nil {
			r.log.Errorf("delete user failed: %s", err.Error())
			return nil, err
		}
	default:
		return nil, fmt.Errorf("invalid delete request: missing id or ids")
	}

	return nil, nil

}

// UserExists is generated from the source proto contract.
func (r *userRepo) UserExists(ctx context.Context, req *identityv1.UserExistsRequest) (*identityv1.UserExistsResponse, error) {

	if req == nil {
		return nil, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().User.Query()
	switch req.GetQueryBy().(type) {

	case *identityv1.UserExistsRequest_Id:
		builder.Where(user.IDEQ(req.GetId()))

	case *identityv1.UserExistsRequest_Username:
		builder.Where(user.UsernameEQ(req.GetUsername()))

	default:
		return &identityv1.UserExistsResponse{Exist: false}, fmt.Errorf("invalid query by type")
	}

	exist, err := builder.Exist(ctx)
	if err != nil {
		r.log.Errorf("query user exists failed: %s", err.Error())
		return nil, err
	}

	return &identityv1.UserExistsResponse{Exist: exist}, nil

}
