// Code generated by ent, DO NOT EDIT.

package dictcategory

import (
	"admin/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldDeletedBy, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldIsEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldSortOrder, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldTenantID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldRemark, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldDescription, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldParentID, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldPath, v))
}

// CategoryKey applies equality check predicate on the "category_key" field. It's identical to CategoryKeyEQ.
func CategoryKey(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCategoryKey, v))
}

// CategoryName applies equality check predicate on the "category_name" field. It's identical to CategoryNameEQ.
func CategoryName(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCategoryName, v))
}

// IsBuiltin applies equality check predicate on the "is_builtin" field. It's identical to IsBuiltinEQ.
func IsBuiltin(v bool) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldIsBuiltin, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldDeletedBy))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldIsEnabled))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldSortOrder, v))
}

// SortOrderIsNil applies the IsNil predicate on the "sort_order" field.
func SortOrderIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldSortOrder))
}

// SortOrderNotNil applies the NotNil predicate on the "sort_order" field.
func SortOrderNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldSortOrder))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldTenantID))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContainsFold(FieldRemark, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContainsFold(FieldDescription, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...uint32) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldParentID))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContainsFold(FieldPath, v))
}

// CategoryKeyEQ applies the EQ predicate on the "category_key" field.
func CategoryKeyEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCategoryKey, v))
}

// CategoryKeyNEQ applies the NEQ predicate on the "category_key" field.
func CategoryKeyNEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldCategoryKey, v))
}

// CategoryKeyIn applies the In predicate on the "category_key" field.
func CategoryKeyIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldCategoryKey, vs...))
}

// CategoryKeyNotIn applies the NotIn predicate on the "category_key" field.
func CategoryKeyNotIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldCategoryKey, vs...))
}

// CategoryKeyGT applies the GT predicate on the "category_key" field.
func CategoryKeyGT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldCategoryKey, v))
}

// CategoryKeyGTE applies the GTE predicate on the "category_key" field.
func CategoryKeyGTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldCategoryKey, v))
}

// CategoryKeyLT applies the LT predicate on the "category_key" field.
func CategoryKeyLT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldCategoryKey, v))
}

// CategoryKeyLTE applies the LTE predicate on the "category_key" field.
func CategoryKeyLTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldCategoryKey, v))
}

// CategoryKeyContains applies the Contains predicate on the "category_key" field.
func CategoryKeyContains(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContains(FieldCategoryKey, v))
}

// CategoryKeyHasPrefix applies the HasPrefix predicate on the "category_key" field.
func CategoryKeyHasPrefix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasPrefix(FieldCategoryKey, v))
}

// CategoryKeyHasSuffix applies the HasSuffix predicate on the "category_key" field.
func CategoryKeyHasSuffix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasSuffix(FieldCategoryKey, v))
}

// CategoryKeyEqualFold applies the EqualFold predicate on the "category_key" field.
func CategoryKeyEqualFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEqualFold(FieldCategoryKey, v))
}

// CategoryKeyContainsFold applies the ContainsFold predicate on the "category_key" field.
func CategoryKeyContainsFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContainsFold(FieldCategoryKey, v))
}

// CategoryNameEQ applies the EQ predicate on the "category_name" field.
func CategoryNameEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCategoryName, v))
}

// CategoryNameNEQ applies the NEQ predicate on the "category_name" field.
func CategoryNameNEQ(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldCategoryName, v))
}

// CategoryNameIn applies the In predicate on the "category_name" field.
func CategoryNameIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldCategoryName, vs...))
}

// CategoryNameNotIn applies the NotIn predicate on the "category_name" field.
func CategoryNameNotIn(vs ...string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldCategoryName, vs...))
}

// CategoryNameGT applies the GT predicate on the "category_name" field.
func CategoryNameGT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGT(FieldCategoryName, v))
}

// CategoryNameGTE applies the GTE predicate on the "category_name" field.
func CategoryNameGTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldGTE(FieldCategoryName, v))
}

// CategoryNameLT applies the LT predicate on the "category_name" field.
func CategoryNameLT(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLT(FieldCategoryName, v))
}

// CategoryNameLTE applies the LTE predicate on the "category_name" field.
func CategoryNameLTE(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldLTE(FieldCategoryName, v))
}

// CategoryNameContains applies the Contains predicate on the "category_name" field.
func CategoryNameContains(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContains(FieldCategoryName, v))
}

// CategoryNameHasPrefix applies the HasPrefix predicate on the "category_name" field.
func CategoryNameHasPrefix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasPrefix(FieldCategoryName, v))
}

// CategoryNameHasSuffix applies the HasSuffix predicate on the "category_name" field.
func CategoryNameHasSuffix(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldHasSuffix(FieldCategoryName, v))
}

// CategoryNameEqualFold applies the EqualFold predicate on the "category_name" field.
func CategoryNameEqualFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEqualFold(FieldCategoryName, v))
}

// CategoryNameContainsFold applies the ContainsFold predicate on the "category_name" field.
func CategoryNameContainsFold(v string) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldContainsFold(FieldCategoryName, v))
}

// CategoryLevelEQ applies the EQ predicate on the "category_level" field.
func CategoryLevelEQ(v CategoryLevel) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldCategoryLevel, v))
}

// CategoryLevelNEQ applies the NEQ predicate on the "category_level" field.
func CategoryLevelNEQ(v CategoryLevel) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldCategoryLevel, v))
}

// CategoryLevelIn applies the In predicate on the "category_level" field.
func CategoryLevelIn(vs ...CategoryLevel) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldCategoryLevel, vs...))
}

// CategoryLevelNotIn applies the NotIn predicate on the "category_level" field.
func CategoryLevelNotIn(vs ...CategoryLevel) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldCategoryLevel, vs...))
}

// SceneEQ applies the EQ predicate on the "scene" field.
func SceneEQ(v Scene) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldScene, v))
}

// SceneNEQ applies the NEQ predicate on the "scene" field.
func SceneNEQ(v Scene) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldScene, v))
}

// SceneIn applies the In predicate on the "scene" field.
func SceneIn(vs ...Scene) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldIn(FieldScene, vs...))
}

// SceneNotIn applies the NotIn predicate on the "scene" field.
func SceneNotIn(vs ...Scene) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNotIn(FieldScene, vs...))
}

// IsBuiltinEQ applies the EQ predicate on the "is_builtin" field.
func IsBuiltinEQ(v bool) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldEQ(FieldIsBuiltin, v))
}

// IsBuiltinNEQ applies the NEQ predicate on the "is_builtin" field.
func IsBuiltinNEQ(v bool) predicate.DictCategory {
	return predicate.DictCategory(sql.FieldNEQ(FieldIsBuiltin, v))
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.DictCategory) predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.DictCategory) predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLabels applies the HasEdge predicate on the "labels" edge.
func HasLabels() predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LabelsTable, LabelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLabelsWith applies the HasEdge predicate on the "labels" edge with a given conditions (other predicates).
func HasLabelsWith(preds ...predicate.DictLabel) predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := newLabelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasI18ns applies the HasEdge predicate on the "i18ns" edge.
func HasI18ns() predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, I18nsTable, I18nsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasI18nsWith applies the HasEdge predicate on the "i18ns" edge with a given conditions (other predicates).
func HasI18nsWith(preds ...predicate.DictCategoryI18n) predicate.DictCategory {
	return predicate.DictCategory(func(s *sql.Selector) {
		step := newI18nsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DictCategory) predicate.DictCategory {
	return predicate.DictCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DictCategory) predicate.DictCategory {
	return predicate.DictCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DictCategory) predicate.DictCategory {
	return predicate.DictCategory(sql.NotPredicates(p))
}
